package app.hirecockpit.api;

import app.hirecockpit.security.WorkspaceContext;
import com.fasterxml.jackson.databind.*;
import jakarta.servlet.http.HttpServletRequest;
import java.io.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.zip.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@RestController
@RequestMapping("/api/v1/backup")
public class BackupController {
    private static final Logger log=LoggerFactory.getLogger(BackupController.class);
    private static final List<String> TABLES=List.of("company","job","resume_version","application","application_status_history","tag","job_tag","dictionary_item","workspace_setting","task","calendar_event","notification_event","stored_file","profile_entry","exam","interview","experience_note","offer","offer_comparison_preference","collection_rule");
    private static final List<String> DELETE_ORDER=List.of("collection_rule","offer_comparison_preference","offer","experience_note","interview","exam","profile_entry","stored_file","notification_event","calendar_event","task","job_tag","tag","application_status_history","application","resume_version","job","company","dictionary_item","workspace_setting");
    private static final long MAX_ARCHIVE=250L*1024*1024;
    private final JdbcTemplate db;private final ObjectMapper json;private final Path uploadRoot;
    public BackupController(JdbcTemplate db,ObjectMapper json,@Value("${app.upload-dir:./data/uploads}")String uploadDir){this.db=db;this.json=json;this.uploadRoot=Path.of(uploadDir).toAbsolutePath().normalize();}

    @GetMapping("/export") public ResponseEntity<ByteArrayResource> export(HttpServletRequest r){String w=workspace(r);Map<String,Object> tables=new LinkedHashMap<>();for(String table:TABLES){String idExpr=table.equals("dictionary_item")?"BIN_TO_UUID(id) AS id":"*";List<Map<String,Object>> rows=db.queryForList("SELECT "+idExpr+" FROM "+table+" WHERE workspace_id=UUID_TO_BIN(?)",w);for(Map<String,Object> row:rows){row.remove("workspace_id");for(Map.Entry<String,Object> cell:row.entrySet())if(cell.getValue() instanceof byte[] binary)cell.setValue(Map.of("$binary",Base64.getEncoder().encodeToString(binary)));}tables.put(table,rows);}List<Map<String,Object>> files=db.queryForList("SELECT id,original_name AS originalName,media_type AS mediaType,file_size AS size,sha256 FROM stored_file WHERE workspace_id=UUID_TO_BIN(?)",w);Map<String,Object> manifest=Map.of("formatVersion",1,"tables",tables,"files",files);try{ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(ZipOutputStream zip=new ZipOutputStream(bytes)){zip.putNextEntry(new ZipEntry("manifest.json"));zip.write(json.writeValueAsBytes(manifest));zip.closeEntry();for(Map<String,Object> file:files){String id=String.valueOf(file.get("id"));Path source=uploadRoot.resolve(w).resolve(id).normalize();if(!source.startsWith(uploadRoot.resolve(w))||!Files.isRegularFile(source,LinkOption.NOFOLLOW_LINKS))throw new ResponseStatusException(HttpStatus.CONFLICT,"A referenced file is missing; backup was not produced");zip.putNextEntry(new ZipEntry("files/"+id));Files.copy(source,zip);zip.closeEntry();if(bytes.size()>MAX_ARCHIVE)throw new ResponseStatusException(HttpStatus.PAYLOAD_TOO_LARGE,"Backup exceeds 250 MiB");}}return ResponseEntity.ok().contentType(MediaType.parseMediaType("application/zip")).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=hire-cockpit-backup.zip").header(HttpHeaders.CACHE_CONTROL,"private, no-store").body(new ByteArrayResource(bytes.toByteArray()));}catch(IOException e){log.error("Workspace backup export failed",e);throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"Backup export failed",e);}}

    @PostMapping(value="/preview",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Map<String,Object> preview(@RequestPart("file") MultipartFile file){Archive a=parse(file);return Map.of("formatVersion",1,"tables",a.tables().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey,e->e.getValue().size(),(x,y)->x,LinkedHashMap::new)),"fileCount",a.files().size(),"totalRows",a.tables().values().stream().mapToInt(List::size).sum(),"sha256Verified",true,"restoreMode","此操作将替换当前工作区中的业务数据，工作区访问密钥保留。请确认预览后再恢复。");}

    @PostMapping(value="/restore",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @Transactional public Map<String,Object> restore(HttpServletRequest r,@RequestPart("file") MultipartFile file){String w=workspace(r);Archive a=parse(file);validateRows(a);Path dir=uploadRoot.resolve(w).normalize();if(!dir.startsWith(uploadRoot))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid workspace path");Map<Path,Path> staged=new LinkedHashMap<>();try{Files.createDirectories(dir);for(Map.Entry<String,byte[]> entry:a.files().entrySet()){Path tmp=Files.createTempFile(dir,".restore-",".tmp");Files.write(tmp,entry.getValue(),StandardOpenOption.WRITE,StandardOpenOption.TRUNCATE_EXISTING);staged.put(dir.resolve(entry.getKey()).normalize(),tmp);}for(String table:DELETE_ORDER)db.update("DELETE FROM "+table+" WHERE workspace_id=UUID_TO_BIN(?)",w);for(String table:TABLES)insertRows(table,a.tables().getOrDefault(table,List.of()),w);for(Map.Entry<Path,Path> pair:staged.entrySet())Files.move(pair.getValue(),pair.getKey(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);return Map.of("restored",true,"tables",a.tables().size(),"rows",a.tables().values().stream().mapToInt(List::size).sum(),"files",a.files().size());}catch(Exception e){for(Path temp:staged.values())try{Files.deleteIfExists(temp);}catch(IOException ignored){}if(e instanceof ResponseStatusException x)throw x;throw new ResponseStatusException(HttpStatus.CONFLICT,"Restore failed; database transaction was rolled back",e);}}

    private Archive parse(MultipartFile upload){if(upload.isEmpty()||upload.getSize()>MAX_ARCHIVE)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Backup is empty or exceeds 250 MiB");try{Map<String,byte[]> entries=new HashMap<>();long total=0;try(ZipInputStream zip=new ZipInputStream(upload.getInputStream())){ZipEntry e;byte[] buffer=new byte[8192];while((e=zip.getNextEntry())!=null){if(e.isDirectory())continue;if(entries.size()>1000)throw bad("Too many archive entries");String name=e.getName();if(name.startsWith("/")||name.contains("..")||name.contains("\\"))throw bad("Invalid archive path");ByteArrayOutputStream out=new ByteArrayOutputStream();int n;while((n=zip.read(buffer))!=-1){total+=n;if(total>MAX_ARCHIVE)throw bad("Expanded backup exceeds 250 MiB");out.write(buffer,0,n);}if(entries.put(name,out.toByteArray())!=null)throw bad("Duplicate archive entry");}}byte[] manifestBytes=entries.remove("manifest.json");if(manifestBytes==null)throw bad("manifest.json is required");JsonNode root=json.readTree(manifestBytes);if(root.path("formatVersion").asInt()!=1)throw bad("Unsupported backup format");JsonNode tableNode=root.path("tables");if(!tableNode.isObject()||!root.path("files").isArray())throw bad("Tables and file manifest are required");Map<String,List<Map<String,Object>>> tables=new LinkedHashMap<>();Iterator<String> names=tableNode.fieldNames();while(names.hasNext()){String table=names.next();if(!TABLES.contains(table))throw bad("Unsupported table: "+table);List<Map<String,Object>> rows=new ArrayList<>();for(JsonNode row:tableNode.path(table)){if(!row.isObject())throw bad("Invalid row in "+table);rows.add(json.convertValue(row,new com.fasterxml.jackson.core.type.TypeReference<>(){}));}tables.put(table,rows);}if(!tables.keySet().containsAll(TABLES))throw bad("Backup is missing required tables");Map<String,byte[]> files=new LinkedHashMap<>();for(JsonNode f:root.path("files")){String id=f.path("id").asText();if(!id.matches("[0-9a-fA-F-]{36}"))throw bad("Invalid file ID");byte[] bytes=entries.remove("files/"+id);if(bytes==null||bytes.length!=f.path("size").asLong()||!sha256(bytes).equalsIgnoreCase(f.path("sha256").asText()))throw bad("File integrity check failed: "+id);files.put(id,bytes);}Set<String> storedIds=new HashSet<>();for(Map<String,Object> row:tables.getOrDefault("stored_file",List.of())){String id=String.valueOf(row.get("id"));byte[] bytes=files.get(id);if(bytes==null||bytes.length!=((Number)row.get("file_size")).longValue()||!sha256(bytes).equalsIgnoreCase(String.valueOf(row.get("sha256"))))throw bad("Stored file metadata does not match its payload: "+id);storedIds.add(id);}if(!storedIds.equals(files.keySet()))throw bad("File manifest does not match stored-file records");if(!entries.isEmpty())throw bad("Unexpected archive entries");return new Archive(tables,files);}catch(ResponseStatusException e){throw e;}catch(Exception e){throw bad("Invalid backup archive: "+e.getMessage());}}
    private void validateRows(Archive a){for(String table:TABLES)for(Map<String,Object> row:a.tables().getOrDefault(table,List.of())){if(row.containsKey("workspace_id")||row.keySet().stream().anyMatch(k->!k.matches("[a-z_]+")))throw bad("Invalid columns in "+table);if(table.equals("stored_file")&&!a.files().containsKey(String.valueOf(row.get("id"))))throw bad("Stored file payload is missing");}}
    private void insertRows(String table,List<Map<String,Object>> rows,String w){for(Map<String,Object> row:rows){List<String> columns=new ArrayList<>(row.keySet());columns.remove("workspace_id");columns.add("workspace_id");String names=String.join(",",columns);String values=columns.stream().map(c->c.equals("workspace_id")?"UUID_TO_BIN(?)":table.equals("dictionary_item")&&c.equals("id")?"UUID_TO_BIN(?)":"?").collect(java.util.stream.Collectors.joining(","));List<Object> params=new ArrayList<>();for(String c:columns){if(c.equals("workspace_id")){params.add(w);continue;}Object value=row.get(c);if(table.equals("profile_entry")&&c.equals("encrypted_payload")&&value instanceof Map<?,?> marker&&marker.containsKey("$binary"))value=Base64.getDecoder().decode(String.valueOf(marker.get("$binary")));if(isJsonColumn(table,c)&&value!=null&&!(value instanceof String))value=json.valueToTree(value).toString();params.add(value);}db.update("INSERT INTO "+table+"("+names+") VALUES("+values+")",params.toArray());}}
    private static boolean isJsonColumn(String t,String c){return (t.equals("dictionary_item")&&false)||((t.equals("company")&&c.equals("payload"))||(t.equals("job")&&c.equals("payload"))||(t.equals("workspace_setting")&&c.equals("setting_value"))||(t.equals("calendar_event")&&c.equals("payload"))||(t.equals("notification_event")&&c.equals("payload"))||(t.equals("profile_entry")&&c.equals("visible_fields"))||(t.equals("exam")&&false)||(t.equals("interview")&&c.equals("question_notes"))||(t.equals("experience_note")&&List.of("questions","answers","tags").contains(c))||(t.equals("offer")&&List.of("benefits","evaluations").contains(c))||(t.equals("offer_comparison_preference")&&c.equals("weights")));}
    private static String sha256(byte[] bytes){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}catch(Exception e){throw new IllegalStateException(e);}}
    private static ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}
    private static String workspace(HttpServletRequest r){Object w=r.getAttribute(WorkspaceContext.ATTRIBUTE);if(w==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);return w.toString();}
    private record Archive(Map<String,List<Map<String,Object>>> tables,Map<String,byte[]> files){}
}
