package app.hirecockpit.api;

import app.hirecockpit.security.WorkspaceContext;
import com.fasterxml.jackson.databind.*;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.*;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@RestController
@RequestMapping("/api/v1")
public class CollectionController {
    private static final int MAX_HTML=2*1024*1024;
    private final JdbcTemplate db;private final ObjectMapper json;
    public CollectionController(JdbcTemplate db,ObjectMapper json){this.db=db;this.json=json;}

    @PostMapping("/recruitment-drafts") public Map<String,Object> draft(HttpServletRequest r,@Valid @RequestBody DraftInput in){workspace(r);URI uri=validatedUri(in.url());String html=fetch(uri);Document doc=Jsoup.parse(html,uri.toString());String structuredTitle=structured(doc,"title"),structuredDescription=structured(doc,"description"),structuredCompany=structured(doc,"hiringOrganization.name"),city=structured(doc,"jobLocation.address.addressLocality"),deadline=structured(doc,"validThrough");doc.select("script,style,noscript,svg,iframe,nav,footer,header").remove();String title=first(doc.title(),meta(doc,"og:title"),doc.selectFirst("h1")!=null?doc.selectFirst("h1").text():null,structuredTitle);String description=first(meta(doc,"og:description"),meta(doc,"description"),structuredDescription,doc.body().text());String company=first(meta(doc,"og:site_name"),structuredCompany);String text=doc.body().text();if(text.length()>32000)text=text.substring(0,32000);return Map.of("sourceUrl",uri.toString(),"title",Objects.toString(title,""),"companyName",Objects.toString(company,""),"city",Objects.toString(city,""),"deadline",isoDate(deadline),"description",description.length()>12000?description.substring(0,12000):description,"originalText",text,"manualConfirmationRequired",true);}

    @GetMapping("/collection-rules") public List<Map<String,Object>> rules(HttpServletRequest r){return db.queryForList("SELECT id,name,keywords,weight,active,created_at AS createdAt,updated_at AS updatedAt FROM collection_rule WHERE workspace_id=UUID_TO_BIN(?) AND deleted_at IS NULL ORDER BY updated_at DESC",workspace(r));}
    @PostMapping("/collection-rules") @ResponseStatus(HttpStatus.CREATED) @Transactional public Map<String,Object> createRule(HttpServletRequest r,@Valid @RequestBody RuleInput in){if(in.keywords()==null||in.keywords().isEmpty()||in.keywords().size()>50||in.keywords().stream().anyMatch(k->k==null||k.isBlank()||k.length()>120)||in.weight()==null||in.weight()<0||in.weight()>100)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Rules need 1–50 keywords and weight from 0 to 100");String w=workspace(r);if(db.queryForObject("SELECT COUNT(*) FROM collection_rule WHERE workspace_id=UUID_TO_BIN(?) AND name=? AND deleted_at IS NULL",Integer.class,w,in.name())>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Rule name already exists");String id=UUID.randomUUID().toString();try{db.update("INSERT INTO collection_rule(id,workspace_id,name,keywords,weight,active) VALUES (?,UUID_TO_BIN(?),?,CAST(? AS JSON),?,?)",id,w,in.name(),json.writeValueAsString(in.keywords().stream().map(String::trim).distinct().toList()),in.weight(),in.active()==null||in.active());}catch(com.fasterxml.jackson.core.JsonProcessingException e){throw new IllegalArgumentException(e);}return Map.of("id",id,"name",in.name());}
    @DeleteMapping("/collection-rules/{id}") @Transactional public void deleteRule(HttpServletRequest r,@PathVariable String id){int n=db.update("UPDATE collection_rule SET deleted_at=UTC_TIMESTAMP(6) WHERE id=? AND workspace_id=UUID_TO_BIN(?) AND deleted_at IS NULL",id,workspace(r));if(n==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Rule not found");}
    @GetMapping("/job-matches") public List<Map<String,Object>> matches(HttpServletRequest r){String w=workspace(r);List<Map<String,Object>> rules=db.queryForList("SELECT id,name,keywords,weight FROM collection_rule WHERE workspace_id=UUID_TO_BIN(?) AND active=TRUE AND deleted_at IS NULL",w);List<Map<String,Object>> jobs=db.queryForList("SELECT j.id,j.title,j.original_text AS originalText,j.notes,j.priority,j.company_id AS companyId,c.name AS companyName FROM job j JOIN company c ON c.id=j.company_id AND c.workspace_id=j.workspace_id WHERE j.workspace_id=UUID_TO_BIN(?) AND j.deleted_at IS NULL",w);List<Map<String,Object>> result=new ArrayList<>();for(Map<String,Object> job:jobs){String haystack=(Objects.toString(job.get("title"),"")+" "+Objects.toString(job.get("originalText"),"")+" "+Objects.toString(job.get("notes"),"")).toLowerCase(Locale.ROOT);double score=0;List<String> reasons=new ArrayList<>();for(Map<String,Object> rule:rules){List<String> keywords=readKeywords(rule.get("keywords"));List<String> matches=keywords.stream().filter(k->haystack.contains(k.toLowerCase(Locale.ROOT))).toList();if(!matches.isEmpty()){score+=matches.size()*((Number)rule.get("weight")).doubleValue();reasons.add(rule.get("name")+": "+String.join(", ",matches));}}job.put("matchScore",Math.round(score*100.0)/100.0);job.put("matchReasons",reasons);result.add(job);}result.sort(Comparator.comparingDouble((Map<String,Object> m)->((Number)m.get("matchScore")).doubleValue()).reversed().thenComparing(m->String.valueOf(m.get("title"))));return result;}

    private URI validatedUri(String raw){try{if(raw==null||raw.length()>2048)throw new IllegalArgumentException();URI u=URI.create(raw.trim()).normalize();String scheme=u.getScheme()==null?"":u.getScheme().toLowerCase(Locale.ROOT);if((!scheme.equals("https")&&!scheme.equals("http"))||u.getHost()==null||u.getUserInfo()!=null||u.getFragment()!=null||!(u.getPort()==-1||scheme.equals("https")&&u.getPort()==443||scheme.equals("http")&&u.getPort()==80))throw new IllegalArgumentException();String host=IDN.toASCII(u.getHost(),IDN.USE_STD3_ASCII_RULES).toLowerCase(Locale.ROOT);if(host.equals("localhost")||host.endsWith(".localhost")||host.endsWith(".local")||host.matches("[0-9.]+")||host.contains(":"))throw new IllegalArgumentException();for(InetAddress address:InetAddress.getAllByName(host))if(!publicAddress(address))throw new IllegalArgumentException();String path=u.getPath()==null||u.getPath().isEmpty()?"/":u.getPath();return new URI(scheme,null,host,u.getPort(),path,u.getQuery(),null);}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Only public HTTP/HTTPS recruitment URLs on standard ports are allowed");}}
    private String fetch(URI uri){HttpURLConnection connection=null;try{connection=(HttpURLConnection)uri.toURL().openConnection();connection.setInstanceFollowRedirects(false);connection.setConnectTimeout(5000);connection.setReadTimeout(7000);connection.setRequestProperty("User-Agent","HireCockpit/1.0 (+recruitment-draft-fetch)");connection.setRequestProperty("Accept","text/html,application/xhtml+xml,text/plain;q=0.8");connection.setRequestProperty("Accept-Encoding","identity");int status=connection.getResponseCode();if(status>=300&&status<400)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Recruitment URL redirected; follow the final address manually");if(status<200||status>=300)throw new ResponseStatusException(HttpStatus.BAD_GATEWAY,"Recruitment page returned HTTP "+status);String type=Objects.toString(connection.getContentType(),"").toLowerCase(Locale.ROOT);if(!(type.contains("text/html")||type.contains("application/xhtml+xml")||type.startsWith("text/plain")))throw new ResponseStatusException(HttpStatus.UNSUPPORTED_MEDIA_TYPE,"Recruitment page is not HTML or text");if(connection.getContentLengthLong()>MAX_HTML)throw new ResponseStatusException(HttpStatus.PAYLOAD_TOO_LARGE,"Recruitment page exceeds 2 MiB");try(InputStream stream=connection.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int n;while((n=stream.read(buffer))!=-1){if(out.size()+n>MAX_HTML)throw new ResponseStatusException(HttpStatus.PAYLOAD_TOO_LARGE,"Recruitment page exceeds 2 MiB");out.write(buffer,0,n);}return out.toString(StandardCharsets.UTF_8);}}catch(ResponseStatusException e){throw e;}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_GATEWAY,"Unable to fetch recruitment page safely",e);}finally{if(connection!=null)connection.disconnect();}}
    private static boolean publicAddress(InetAddress a){if(a.isAnyLocalAddress()||a.isLoopbackAddress()||a.isLinkLocalAddress()||a.isSiteLocalAddress()||a.isMulticastAddress())return false;byte[] b=a.getAddress();if(b.length==4){int x=b[0]&255,y=b[1]&255;if(x==0||x==100&&y>=64&&y<=127||x==192&&y==0||x==198&&(y==18||y==19)||x>=224)return false;}else if(b.length==16){int x=b[0]&255,y=b[1]&255;if((x&0xfe)==0xfc||x==0xfe&&(y&0xc0)==0x80||(x==0&&b[15]==1))return false;if(Arrays.stream(new int[]{0,1,2,3,4,5,6,7,8,9}).allMatch(i->b[i]==0)&&(b[10]&255)==255&&(b[11]&255)==255){try{return publicAddress(InetAddress.getByAddress(Arrays.copyOfRange(b,12,16)));}catch(UnknownHostException e){return false;}}}return true;}
    private String structured(Document doc,String path){for(var script:doc.select("script[type=application/ld+json]"))try{JsonNode root=json.readTree(script.data());JsonNode found=findJobPosting(root);for(String key:path.split("\\.")){if(found==null)return null;found=key.equals("hiringOrganization.name")?found.path("hiringOrganization").path("name"):key.equals("jobLocation.address.addressLocality")?found.path("jobLocation").path("address").path("addressLocality"):found.path(key);}if(found!=null&&!found.isMissingNode()&&!found.isNull())return found.isTextual()?found.asText():found.toString();}catch(Exception ignored){}return null;}
    private JsonNode findJobPosting(JsonNode node){if(node.isObject()){if(node.path("@type").asText("").contains("JobPosting"))return node;for(JsonNode child:node) {JsonNode found=findJobPosting(child);if(found!=null)return found;}}else if(node.isArray())for(JsonNode child:node){JsonNode found=findJobPosting(child);if(found!=null)return found;}return null;}
    private static String meta(Document d,String name){var m=d.selectFirst("meta[property=\""+name+"\"],meta[name=\""+name+"\"]");return m==null?null:m.attr("content");}
    private static String first(String...values){for(String v:values)if(v!=null&&!v.isBlank())return v.trim();return null;}
    private static String isoDate(String v){if(v==null||v.isBlank())return "";try{return LocalDate.parse(v.substring(0,10)).toString();}catch(Exception e){return "";}}
    private static List<String> readKeywords(Object raw){try{if(raw instanceof String s)return new ObjectMapper().readValue(s,new com.fasterxml.jackson.core.type.TypeReference<>(){});if(raw instanceof List<?> l)return l.stream().map(String::valueOf).toList();}catch(Exception ignored){}return List.of();}
    private static String workspace(HttpServletRequest r){Object w=r.getAttribute(WorkspaceContext.ATTRIBUTE);if(w==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);return w.toString();}
    public record DraftInput(@NotBlank String url){}
    public record RuleInput(@NotBlank String name,List<String> keywords,Double weight,Boolean active){}
}
