package app.hirecockpit.api;

import app.hirecockpit.security.WorkspaceContext;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import java.math.BigDecimal;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@RestController
@RequestMapping("/api/v1")
public class OfferController {
    private static final Map<String,Double> DEFAULTS=Map.of("compensation",0.35,"growth",0.25,"role",0.20,"location",0.10,"culture",0.10);
    private final JdbcTemplate db; private final ObjectMapper json;
    public OfferController(JdbcTemplate db,ObjectMapper json){this.db=db;this.json=json;}

    @GetMapping("/offers") public List<Map<String,Object>> offers(HttpServletRequest r){return db.queryForList("SELECT o.id,o.application_id AS applicationId,c.name AS companyName,j.title AS jobTitle,o.base_salary AS baseSalary,o.bonus,o.equity,o.benefits,o.evaluations,o.work_city AS workCity,o.work_mode AS workMode,o.received_at AS receivedAt,o.response_deadline AS responseDeadline,o.decision,o.notes FROM offer o JOIN application a ON a.id=o.application_id AND a.workspace_id=o.workspace_id JOIN job j ON j.id=a.job_id AND j.workspace_id=a.workspace_id JOIN company c ON c.id=j.company_id AND c.workspace_id=j.workspace_id WHERE o.workspace_id=UUID_TO_BIN(?) AND o.deleted_at IS NULL ORDER BY o.updated_at DESC",workspace(r));}
    @PostMapping("/offers") @ResponseStatus(HttpStatus.CREATED) @Transactional public Map<String,Object> create(HttpServletRequest r,@Valid @RequestBody OfferInput in){String w=workspace(r),id=UUID.randomUUID().toString();requireApplication(w,in.applicationId());decision(in.decision());evaluations(in.evaluations());db.update("INSERT INTO offer(id,workspace_id,application_id,base_salary,bonus,equity,benefits,evaluations,work_city,work_mode,received_at,response_deadline,decision,notes) VALUES (?,UUID_TO_BIN(?),?,?,?,?,CAST(? AS JSON),CAST(? AS JSON),?,?,?,?,?,?)",id,w,in.applicationId(),in.baseSalary(),in.bonus(),in.equity(),write(in.benefits()),write(in.evaluations()),in.workCity(),in.workMode(),in.receivedAt(),in.responseDeadline(),normalDecision(in.decision()),in.notes());db.update("UPDATE application SET current_stage='OFFER',current_status='Offer' WHERE id=? AND workspace_id=UUID_TO_BIN(?)",in.applicationId(),w);db.update("INSERT INTO application_status_history(id,workspace_id,application_id,status_snapshot,stable_stage,note) VALUES (?,UUID_TO_BIN(?),?,'Offer','OFFER','收到 Offer')",UUID.randomUUID().toString(),w,in.applicationId());return Map.of("id",id,"applicationId",in.applicationId());}
    @PutMapping("/offers/{id}") @Transactional public Map<String,Object> update(HttpServletRequest r,@PathVariable String id,@Valid @RequestBody OfferInput in){String w=workspace(r);requireApplication(w,in.applicationId());decision(in.decision());evaluations(in.evaluations());int n=db.update("UPDATE offer SET application_id=?,base_salary=?,bonus=?,equity=?,benefits=CAST(? AS JSON),evaluations=CAST(? AS JSON),work_city=?,work_mode=?,received_at=?,response_deadline=?,decision=?,notes=? WHERE id=? AND workspace_id=UUID_TO_BIN(?) AND deleted_at IS NULL",in.applicationId(),in.baseSalary(),in.bonus(),in.equity(),write(in.benefits()),write(in.evaluations()),in.workCity(),in.workMode(),in.receivedAt(),in.responseDeadline(),normalDecision(in.decision()),in.notes(),id,w);if(n==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Offer not found");return Map.of("id",id);}
    @DeleteMapping("/offers/{id}") @Transactional public void delete(HttpServletRequest r,@PathVariable String id){int n=db.update("UPDATE offer SET deleted_at=UTC_TIMESTAMP(6) WHERE id=? AND workspace_id=UUID_TO_BIN(?) AND deleted_at IS NULL",id,workspace(r));if(n==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Offer not found");}
    @GetMapping("/analytics") public Map<String,Object> analytics(HttpServletRequest r){String w=workspace(r);List<Map<String,Object>> funnel=db.queryForList("SELECT current_stage AS stage,COUNT(*) AS count FROM application WHERE workspace_id=UUID_TO_BIN(?) AND deleted_at IS NULL GROUP BY current_stage ORDER BY current_stage",w);List<Map<String,Object>> monthly=db.queryForList("SELECT DATE_FORMAT(applied_at,'%Y-%m') AS month,COUNT(*) AS count FROM application WHERE workspace_id=UUID_TO_BIN(?) AND deleted_at IS NULL AND applied_at IS NOT NULL GROUP BY DATE_FORMAT(applied_at,'%Y-%m') ORDER BY month",w);Map<String,Object> sources=new LinkedHashMap<>();for(Map<String,Object> row:db.queryForList("SELECT COALESCE(channel,'未填写') AS channel,COUNT(*) AS count FROM application WHERE workspace_id=UUID_TO_BIN(?) AND deleted_at IS NULL GROUP BY channel ORDER BY count DESC",w))sources.put(String.valueOf(row.get("channel")),row.get("count"));return Map.of("funnel",funnel,"monthlyApplications",monthly,"channels",sources);}
    @GetMapping("/offers/comparison-preferences") public Map<String,Object> weights(HttpServletRequest r){String w=workspace(r);List<String> values=db.query("SELECT CAST(weights AS CHAR) FROM offer_comparison_preference WHERE workspace_id=UUID_TO_BIN(?)",(rs,n)->rs.getString(1),w);if(values.isEmpty())return Map.of("weights",DEFAULTS);try{return Map.of("weights",json.readValue(values.get(0),Map.class));}catch(Exception e){throw new IllegalStateException(e);}}
    @PutMapping("/offers/comparison-preferences") @Transactional public Map<String,Object> saveWeights(HttpServletRequest r,@RequestBody WeightInput in){if(in.weights()==null||!in.weights().keySet().equals(DEFAULTS.keySet())||in.weights().values().stream().anyMatch(v->v==null||!Double.isFinite(v)||v<0)||Math.abs(in.weights().values().stream().mapToDouble(Double::doubleValue).sum()-1)>0.0001)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Provide compensation, growth, role, location and culture weights that sum to 1");String w=workspace(r);db.update("INSERT INTO offer_comparison_preference(workspace_id,weights) VALUES(UUID_TO_BIN(?),CAST(? AS JSON)) ON DUPLICATE KEY UPDATE weights=VALUES(weights)",w,write(in.weights()));return Map.of("weights",in.weights());}
    @GetMapping("/offers/comparison") public Map<String,Object> compare(HttpServletRequest r){Map<String,Double> weights=(Map<String,Double>)weights(r).get("weights");double total=weights.values().stream().mapToDouble(Double::doubleValue).sum();List<Map<String,Object>> offers=offers(r);for(Map<String,Object> offer:offers){double score=0;Object salary=offer.get("baseSalary");double salaryValue=salary instanceof Number n?n.doubleValue():0;Object raw=offer.get("evaluations");Map<?,?> eval=raw instanceof Map<?,?> m?m:Map.of();if(raw instanceof String s)try{eval=json.readValue(s,Map.class);}catch(Exception ignored){}for(Map.Entry<String,Double> criterion:weights.entrySet()){String key=criterion.getKey();double value=key.equals("compensation")?salaryValue:number(eval.get(key));double normalized=key.equals("compensation")?Math.min(100,salaryValue/1000):Math.max(0,Math.min(100,value));score+=normalized*criterion.getValue();}offer.put("comparisonScore",Math.round(score*100.0)/100.0);}return Map.of("weights",weights,"offers",offers,"weightTotal",total);}
    private static double number(Object o){return o instanceof Number n?n.doubleValue():0;}
    private void requireApplication(String w,String id){if(db.queryForObject("SELECT COUNT(*) FROM application WHERE id=? AND workspace_id=UUID_TO_BIN(?) AND deleted_at IS NULL",Integer.class,id,w)==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Application not found");}
    private static String workspace(HttpServletRequest r){Object w=r.getAttribute(WorkspaceContext.ATTRIBUTE);if(w==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);return w.toString();}
    private static String normalDecision(String s){return s==null||s.isBlank()?"待决定":s;}
    private static void decision(String s){if(s!=null&&!Set.of("待决定","已接受","已拒绝","已过期").contains(s))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid Offer decision");}
    private static void evaluations(Map<String,Integer> values){if(values==null)return;if(values.keySet().stream().anyMatch(k->!Set.of("growth","role","location","culture").contains(k))||values.values().stream().anyMatch(v->v==null||v<0||v>100))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Evaluation scores must use known criteria from 0 to 100");}
    private String write(Object o){try{return json.writeValueAsString(o==null?Map.of():o);}catch(JsonProcessingException e){throw new IllegalArgumentException(e);}}
    public record OfferInput(@NotBlank String applicationId,BigDecimal baseSalary,BigDecimal bonus,BigDecimal equity,Object benefits,Map<String,Integer> evaluations,String workCity,String workMode,java.time.LocalDate receivedAt,java.time.LocalDate responseDeadline,String decision,String notes){}
    public record WeightInput(Map<String,Double> weights){}
}
