<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from './api'
import { stableStage } from './workflow'
type Company = {id:string;name:string;shortName?:string;region?:string;nature?:string}
type Job = {id:string;companyId:string;companyName:string;title:string;city?:string;deadline?:string;favorite:boolean;priority:string}
type Application = {id:string;jobId:string;jobTitle:string;companyName:string;status:string;stage:string;appliedAt?:string}
type Resume = {id:string;name:string;direction?:string;version?:string;storedFileId?:string}
type Task = {id:string;title:string;taskType:string;priority:string;dueAt?:string;timeZone?:string;completed:boolean;jobId?:string}
type CalendarEvent = {id:string;title:string;eventType:string;startsAt:string;endsAt?:string;sourceType:string;timeZone?:string}
type Notification = {id:string;title:string;dueAt:string;readAt?:string}
type ProfileEntry = {id:string;title:string;fields:Record<string,unknown>;visibleFields:string[]}
const active = ref('驾驶舱'), nav = ['驾驶舱','企业','岗位','投递','日程','简历与材料','个人资料','笔试与面试','Offer','数据分析','设置']
const companies=ref<Company[]>([]), jobs=ref<Job[]>([]), applications=ref<Application[]>([]), resumes=ref<Resume[]>([]), tasks=ref<Task[]>([]), calendarEvents=ref<CalendarEvent[]>([]), notifications=ref<Notification[]>([]), error=ref(''), loading=ref(true)
const companyDialog=ref(false),jobDialog=ref(false),applicationDialog=ref(false),resumeDialog=ref(false),taskDialog=ref(false),notificationDialog=ref(false)
const companyDraft=reactive({name:'',shortName:'',nature:'',industry:'',region:'',website:'',recruitmentWebsite:'',description:'',notes:''})
const resumeDraft=reactive({name:'',direction:'',version:'',notes:'',storedFileId:''})
const taskDraft=reactive({title:'',taskType:'其他',priority:'B',dueAt:'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,jobId:''})
const reminderDays=ref<number[]>([7,3,1,0]),reminderZone=ref(Intl.DateTimeFormat().resolvedOptions().timeZone)
const profileEntries=ref<ProfileEntry[]>([]),profileSection=ref('personal'),profileDialog=ref(false),profileTitle=ref(''),profileFieldsText=ref('姓名=\n手机号=\n邮箱=')
const profileSections=[['personal','基本信息'],['contact','联系方式'],['education','教育经历'],['project','项目经历'],['research','科研经历'],['internship','实习经历'],['skill','技能'],['certificate','证书'],['award','获奖'],['language','语言']] as const
const exams=ref<any[]>([]),interviews=ref<any[]>([]),experienceNotes=ref<any[]>([]),practiceTab=ref<'exam'|'interview'|'notes'>('exam'),examDialog=ref(false),interviewDialog=ref(false),experienceDialog=ref(false)
const examDraft=reactive({applicationId:'',platform:'',startsAt:'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,examUrl:'',admissionUrl:'',score:undefined as number|undefined,result:'',reflection:'',notes:''})
const interviewDraft=reactive({applicationId:'',roundName:'一面',startsAt:'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,modality:'线上',location:'',interviewer:'',rating:undefined as number|undefined,result:'',review:'',notes:''})
const experienceDraft=reactive({companyId:'',jobId:'',roundName:'',title:'',questions:'',answers:'',tags:'',source:''})
const offers=ref<any[]>([]),analytics=ref<any>({funnel:[],monthlyApplications:[],channels:{}}),offerDialog=ref(false),comparisonWeights=reactive<Record<string,number>>({compensation:.35,growth:.25,role:.2,location:.1,culture:.1})
const comparisonLabels:Record<string,string>={compensation:'薪酬',growth:'成长',role:'岗位匹配',location:'地点',culture:'文化'}
const offerDraft=reactive({applicationId:'',baseSalary:undefined as number|undefined,bonus:undefined as number|undefined,equity:undefined as number|undefined,workCity:'',workMode:'',receivedAt:'',responseDeadline:'',decision:'待决定',notes:'',evaluations:{growth:70,role:70,location:70,culture:70} as Record<string,number>})
const jobDraft=reactive({companyId:'',title:'',department:'',jobNumber:'',recruitmentType:'秋招',batch:'',city:'',degreeRequirement:'',majorRequirement:'',skillRequirement:'',salary:'',deadline:'',sourceUrl:'',notes:'',favorite:false,priority:'B'})
const applicationDraft=reactive({jobId:'',resumeVersionId:'',channel:'',platform:'',referrer:'',notes:'',status:'已投递',stage:'APPLICATION'})
const counts=computed(()=>({companies:companies.value.length,favorites:jobs.value.filter(j=>j.favorite).length,applied:applications.value.length,interviews:applications.value.filter(a=>a.stage==='INTERVIEW').length,offers:applications.value.filter(a=>a.stage==='OFFER').length}))
const unreadNotifications=computed(()=>notifications.value.filter(n=>!n.readAt).length)
const viewMode=ref<'month'|'week'|'day'>('week'),cursorDate=ref(new Date())
const calendarModes=['day','week','month'] as const,modeLabels:Record<'day'|'week'|'month',string>={day:'日',week:'周',month:'月'}
function dateKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function startOfWeek(d:Date){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());x.setDate(x.getDate()-(x.getDay()+6)%7);return x}
const calendarStart=computed(()=>viewMode.value==='day'?new Date(cursorDate.value.getFullYear(),cursorDate.value.getMonth(),cursorDate.value.getDate()):viewMode.value==='week'?startOfWeek(cursorDate.value):startOfWeek(new Date(cursorDate.value.getFullYear(),cursorDate.value.getMonth(),1)))
const calendarLength=computed(()=>viewMode.value==='day'?1:viewMode.value==='week'?7:42)
const calendarDays=computed(()=>Array.from({length:calendarLength.value},(_,i)=>{const d=new Date(calendarStart.value);d.setDate(d.getDate()+i);return d}))
const calendarTitle=computed(()=>viewMode.value==='day'?cursorDate.value.toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'}):viewMode.value==='week'?`${dateKey(calendarDays.value[0])} — ${dateKey(calendarDays.value[6])}`:cursorDate.value.toLocaleDateString('zh-CN',{year:'numeric',month:'long'}))
const todayTasks=computed(()=>{const k=dateKey(new Date());return tasks.value.filter(t=>!t.completed&&t.dueAt&&dateKey(new Date(t.dueAt))===k)})
const eventsForDay=(d:Date)=>calendarEvents.value.filter(e=>dateKey(new Date(e.startsAt))===dateKey(d))
async function loadCalendar(){const start=calendarStart.value,end=new Date(start);end.setDate(end.getDate()+calendarLength.value);try{calendarEvents.value=(await api.get('/calendar',{params:{from:start.toISOString(),to:end.toISOString()}})).data}catch{error.value='日历加载失败'}}
function shiftCalendar(direction:number){const d=new Date(cursorDate.value);if(viewMode.value==='month'){d.setDate(1);d.setMonth(d.getMonth()+direction)}else if(viewMode.value==='week')d.setDate(d.getDate()+7*direction);else d.setDate(d.getDate()+direction);cursorDate.value=d;void loadCalendar()}
async function openSection(item:string){active.value=item;if(item==='日程')await loadCalendar();if(item==='个人资料')await loadProfile();if(item==='笔试与面试')await loadPractice();if(item==='Offer')await loadOffers();if(item==='数据分析')await loadAnalytics()}
async function loadOffers(){try{const [items,settings]=await Promise.all([api.get('/offers/comparison'),api.get('/offers/comparison-preferences')]);offers.value=items.data.offers;Object.assign(comparisonWeights,settings.data.weights)}catch{error.value='Offer 对比数据加载失败'}}
async function loadAnalytics(){try{analytics.value=(await api.get('/analytics')).data}catch{error.value='数据分析加载失败'}}
async function saveComparisonWeights(){const total=Object.values(comparisonWeights).reduce((a,b)=>a+b,0);if(Math.abs(total-1)>.0001){error.value='比较权重总和必须为 100%';return}try{await api.put('/offers/comparison-preferences',{weights:{...comparisonWeights}});await loadOffers()}catch(e:any){error.value=e?.response?.data?.detail||'比较权重保存失败'}}
async function createOffer(){try{await api.post('/offers',{...offerDraft,baseSalary:offerDraft.baseSalary??null,bonus:offerDraft.bonus??null,equity:offerDraft.equity??null,receivedAt:offerDraft.receivedAt||null,responseDeadline:offerDraft.responseDeadline||null});offerDialog.value=false;await load();await loadOffers()}catch(e:any){error.value=e?.response?.data?.detail||'Offer 保存失败'}}
async function loadPractice(){try{[exams.value,interviews.value,experienceNotes.value]=await Promise.all([api.get('/exams').then(r=>r.data),api.get('/interviews').then(r=>r.data),api.get('/experience-notes').then(r=>r.data)])}catch{error.value='笔面试记录加载失败'}}
function openPractice(tab:'exam'|'interview'|'notes'){practiceTab.value=tab;void loadPractice()}
function toIso(value:string){return value?new Date(value).toISOString():null}
async function createExam(){try{await api.post('/exams',{...examDraft,startsAt:toIso(examDraft.startsAt),score:examDraft.score??null,applicationId:examDraft.applicationId||null});examDialog.value=false;Object.assign(examDraft,{applicationId:'',platform:'',startsAt:'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,examUrl:'',admissionUrl:'',score:undefined,result:'',reflection:'',notes:''});await loadPractice();await loadCalendar()}catch(e:any){error.value=e?.response?.data?.detail||'笔试记录保存失败'}}
async function createInterview(){try{await api.post('/interviews',{...interviewDraft,startsAt:toIso(interviewDraft.startsAt),rating:interviewDraft.rating??null,questionNotes:[],applicationId:interviewDraft.applicationId});interviewDialog.value=false;await loadPractice();await loadCalendar()}catch(e:any){error.value=e?.response?.data?.detail||'面试记录保存失败'}}
async function createExperience(){try{await api.post('/experience-notes',{...experienceDraft,companyId:experienceDraft.companyId||null,jobId:experienceDraft.jobId||null,questions:experienceDraft.questions.split(/\r?\n/).filter(Boolean),answers:experienceDraft.answers.split(/\r?\n/).filter(Boolean),tags:experienceDraft.tags.split(',').map(x=>x.trim()).filter(Boolean)});experienceDialog.value=false;await loadPractice()}catch(e:any){error.value=e?.response?.data?.detail||'面经保存失败'}}
async function loadProfile(){try{profileEntries.value=(await api.get(`/profiles/${profileSection.value}`)).data}catch(e:any){error.value=e?.response?.data?.detail||'个人资料加载失败'}}
function chooseProfileSection(section:string){profileSection.value=section;void loadProfile()}
function parseProfileFields(){const fields:Record<string,string>={};for(const line of profileFieldsText.value.split(/\r?\n/)){const i=line.indexOf('=');if(i>0){const key=line.slice(0,i).trim(),value=line.slice(i+1).trim();if(key&&value)fields[key]=value}}return fields}
async function createProfile(){const fields=parseProfileFields();if(!Object.keys(fields).length){error.value='请至少填写一个字段，格式为“字段名=内容”';return}try{await api.post(`/profiles/${profileSection.value}`,{title:profileTitle.value||profileSections.find(x=>x[0]===profileSection.value)?.[1]||'资料',fields});profileDialog.value=false;profileTitle.value='';profileFieldsText.value='';error.value='';await loadProfile()}catch(e:any){error.value=e?.response?.data?.detail||'个人资料保存失败；保存前请配置 APP_ENCRYPTION_KEY'}}
async function toggleProfileVisibility(entry:ProfileEntry,key:string){const visible=entry.visibleFields.includes(key)?entry.visibleFields.filter(x=>x!==key):[...entry.visibleFields,key];try{await api.put(`/profiles/${profileSection.value}/${entry.id}`,{title:entry.title,fields:entry.fields,visibleFields:visible});await loadProfile()}catch{error.value='资料可见字段保存失败'}}
async function copyValue(value:unknown){try{await navigator.clipboard.writeText(String(value));error.value='已复制到剪贴板'}catch{error.value='剪贴板访问失败，请检查浏览器权限'}}
async function load(){loading.value=true;error.value='';try{await api.get('/workspaces/current');[companies.value,jobs.value,applications.value,resumes.value,tasks.value]=await Promise.all([api.get('/companies').then(r=>r.data),api.get('/jobs').then(r=>r.data),api.get('/applications').then(r=>r.data),api.get('/resumes').then(r=>r.data),api.get('/tasks').then(r=>r.data)]);const prefs=(await api.get('/settings/reminders')).data;reminderDays.value=prefs.days;reminderZone.value=prefs.timeZone;await loadCalendar();await refreshNotifications()}catch(e:any){error.value=e?.response?.data?.title||'暂时无法加载工作区，请检查服务连接'}finally{loading.value=false}}
async function saveReminderPreferences(){try{const r=await api.put('/settings/reminders',{days:reminderDays.value,timeZone:reminderZone.value});reminderDays.value=r.data.days;reminderZone.value=r.data.timeZone;await refreshNotifications()}catch(e:any){error.value=e?.response?.data?.detail||'提醒规则保存失败'}}
async function createCompany(){try{await api.post('/companies',companyDraft);companyDialog.value=false;Object.assign(companyDraft,{name:'',shortName:'',nature:'',industry:'',region:'',website:'',recruitmentWebsite:'',description:'',notes:''});await load()}catch(e:any){error.value=e?.response?.data?.detail||'企业保存失败'}}
async function attachResumeFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{const form=new FormData();form.append('file',file);const r=await api.post('/files',form);resumeDraft.storedFileId=r.data.id;error.value=''}catch(e:any){resumeDraft.storedFileId='';error.value=e?.response?.data?.detail||'文件上传失败'}}
function downloadFile(id:string){window.location.assign(`/api/v1/files/${id}/download`)}
async function createResume(){try{await api.post('/resumes',{...resumeDraft,storedFileId:resumeDraft.storedFileId||null});resumeDialog.value=false;Object.assign(resumeDraft,{name:'',direction:'',version:'',notes:'',storedFileId:''});await load()}catch(e:any){error.value=e?.response?.data?.detail||'简历版本保存失败'}}
async function createTask(){try{await api.post('/tasks',{title:taskDraft.title,taskType:taskDraft.taskType,priority:taskDraft.priority,timeZone:taskDraft.timeZone,dueAt:taskDraft.dueAt?new Date(taskDraft.dueAt).toISOString():null,jobId:taskDraft.jobId||null});taskDialog.value=false;Object.assign(taskDraft,{title:'',taskType:'其他',priority:'B',dueAt:'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,jobId:''});await load()}catch(e:any){error.value=e?.response?.data?.detail||'待办保存失败'}}
async function completeTask(task:Task){try{await api.put(`/tasks/${task.id}/complete`,{completed:!task.completed});await load()}catch{error.value='待办状态更新失败'}}
async function refreshNotifications(){try{notifications.value=(await api.get('/notifications')).data}catch{}}
async function showNotifications(){notificationDialog.value=true;await refreshNotifications()}
async function readNotification(item:Notification){try{await api.put(`/notifications/${item.id}/read`,{});notifications.value=notifications.value.map(n=>n.id===item.id?{...n,readAt:new Date().toISOString()}:n)}catch{error.value='提醒状态更新失败'}}
async function createJob(){try{await api.post('/jobs',{...jobDraft,deadline:jobDraft.deadline||null});jobDialog.value=false;Object.assign(jobDraft,{companyId:'',title:'',department:'',jobNumber:'',recruitmentType:'秋招',batch:'',city:'',degreeRequirement:'',majorRequirement:'',skillRequirement:'',salary:'',deadline:'',sourceUrl:'',notes:'',favorite:false,priority:'B'});await load()}catch(e:any){error.value=e?.response?.data?.detail||'岗位保存失败'}}
async function createApplication(){try{await api.post('/applications',{...applicationDraft,resumeVersionId:applicationDraft.resumeVersionId||null});applicationDialog.value=false;Object.assign(applicationDraft,{jobId:'',resumeVersionId:'',channel:'',platform:'',referrer:'',notes:'',status:'已投递',stage:'APPLICATION'});await load()}catch(e:any){error.value=e?.response?.data?.detail||'投递保存失败'}}
async function toggleFavorite(job:Job){try{await api.post(`/jobs/${job.id}/favorite`,{favorite:!job.favorite});await load()}catch(e:any){error.value='收藏状态更新失败'}}
async function changeStatus(item:Application,event:Event){const target=(event.target as HTMLSelectElement).value;if(!target)return;const stage=stableStage(target);if(!stage){error.value='此状态尚未配置阶段映射';return}try{await api.put(`/applications/${item.id}/status`,{status:target,stage,note:'工作台更新'});await load()}catch(e:any){error.value='状态更新失败'}}
async function viewHistory(id:string){try{const r=await api.get(`/applications/${id}/history`);window.alert(r.data.map((h:any)=>`${h.status} · ${h.changedAt}`).join('\n'))}catch{error.value='无法读取该投递的状态历史'}}
onMounted(load)
</script>

<template>
  <div class="shell">
    <aside class="sidebar"><div class="brand"><span class="brand-mark">H</span><div><b>Hire Cockpit</b><small>秋招工作台</small></div></div><div class="workspace"><span class="avatar">我</span><div><b>我的求职工作区</b><small>仅此浏览器可继续使用</small></div><span class="chevron">⌄</span></div><nav><button v-for="(item,i) in nav" :key="item" :class="{selected:active===item}" @click="openSection(item)"><span class="nav-icon">{{ ['⌂','▤','◈','↗','▦','▱','◉','✳','◇','▥','⚙'][i] }}</span>{{item}}</button></nav><div class="sidebar-bottom"><span class="online-dot"></span> 数据保存在安全工作区 <span class="help">?</span></div></aside>
    <main class="main"><header class="topbar"><div class="crumb">工作台 <span>/</span> {{active}}</div><div class="top-actions"><button class="search">⌕ <span>搜索企业、岗位、标签...</span><kbd>⌘ K</kbd></button><button class="icon-btn" aria-label="提醒" @click="showNotifications">♧<span v-if="unreadNotifications" class="notification-count">{{unreadNotifications}}</span></button><button class="user-chip"><span class="avatar">我</span> 我的工作区⌄</button></div></header>
      <section class="content" v-if="active==='驾驶舱'"><div class="welcome"><div><div class="eyebrow">HIRE COCKPIT <span class="sun">☼</span></div><h1>早上好，准备好开启新的一天了吗？</h1><p>每一步积累，都会让理想的机会离你更近。</p></div><button class="primary" @click="active='岗位'">＋ 添加新岗位</button></div>
        <div v-if="error" class="error-banner" role="alert">{{error}} <button @click="load">重试</button></div>
        <div class="stats"><article class="stat-card"><div class="stat-top"><span>已收藏岗位</span><span class="stat-icon lilac">♡</span></div><div class="stat-value">{{counts.favorites}} <small>个</small></div><div class="stat-note">来自当前浏览器工作区</div></article><article class="stat-card"><div class="stat-top"><span>已投递</span><span class="stat-icon blue">↗</span></div><div class="stat-value">{{counts.applied}} <small>个</small></div><div class="stat-note">所有申请，一目了然</div></article><article class="stat-card"><div class="stat-top"><span>面试进行中</span><span class="stat-icon amber">♧</span></div><div class="stat-value">{{counts.interviews}} <small>场</small></div><div class="stat-note">认真准备，从容应对</div></article><article class="stat-card"><div class="stat-top"><span>收获 Offer</span><span class="stat-icon green">◇</span></div><div class="stat-value">{{counts.offers}} <small>份</small></div><div class="stat-note">{{counts.companies}} 家企业记录</div></article></div>
        <div class="grid-main"><article class="panel pipeline"><div class="panel-head"><div><h2>求职进展</h2><p>从发现机会到收获 Offer</p></div><button class="text-button" @click="openSection('数据分析')">查看分析 →</button></div><div class="funnel-empty"><div class="funnel-art"><span>♡</span><span>↗</span><span>✳</span><span>◇</span></div><b v-if="applications.length===0">{{loading?'正在加载…':'你的求职故事，从这里开始'}}</b><b v-else>已记录 {{applications.length}} 条投递</b><p v-if="applications.length===0">添加第一个岗位，开启你的求职旅程</p><button class="outline" @click="openSection('岗位')">去添加岗位 →</button></div></article><article class="panel today"><div class="panel-head"><div><h2>今日安排</h2><p>{{todayTasks.length}} 项待办</p></div><button class="round-add" @click="openSection('日程')">＋</button></div><div v-if="todayTasks.length" class="today-list"><label v-for="task in todayTasks" :key="task.id"><input type="checkbox" :checked="task.completed" @change="completeTask(task)"><span>{{task.title}}</span><small>{{new Date(task.dueAt!).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></label></div><div v-else class="empty-task"><span>☼</span><b>{{loading?'正在加载…':'今天还没有待办'}}</b><p>给自己定个小目标吧</p><button class="text-button" @click="openSection('日程')">＋ 创建任务</button></div></article></div>
        <div class="bottom-grid"><article class="panel deadlines"><div class="panel-head"><div><h2>近期截止</h2><p>别错过重要的时间节点</p></div><button class="text-button" @click="active='岗位'">全部岗位 →</button></div><div class="no-deadline">{{jobs.filter(j=>j.deadline).length?jobs.filter(j=>j.deadline).map(j=>`${j.title} · ${j.deadline}`).join('　'): '暂无即将截止的事项'}}</div></article><article class="tip"><span class="tip-spark">✦</span><div><small>工作区安全提示</small><p>清除 Cookie 或更换设备前，请先导出数据备份。</p><button @click="active='设置'">了解数据管理 →</button></div><span class="tip-orb"></span></article></div><footer>© 2026 Hire Cockpit <span>用心规划，静待花开 <b>✳</b></span></footer>
      </section>
      <section v-else class="content placeholder"><div class="welcome"><div><div class="eyebrow">HIRE COCKPIT · {{active}}</div><h1>{{active}}</h1><p>{{error||'管理你的求职信息与进展。'}}</p></div><div class="toolbar"><button v-if="active==='企业'" class="primary" @click="companyDialog=true">＋ 新建企业</button><button v-if="active==='岗位'" class="primary" @click="jobDialog=true" :disabled="companies.length===0">＋ 新建岗位</button><button v-if="active==='投递'" class="primary" @click="applicationDialog=true" :disabled="jobs.length===0">＋ 新建投递</button><button v-if="active==='Offer'" class="primary" @click="offerDialog=true" :disabled="applications.length===0">＋ 记录 Offer</button><button v-if="active==='简历与材料'" class="primary" @click="resumeDialog=true">＋ 添加简历版本</button><button v-if="active==='日程'" class="primary" @click="taskDialog=true">＋ 新建待办</button><button v-if="active==='笔试与面试'&&practiceTab==='exam'" class="primary" @click="examDialog=true">＋ 添加笔试</button><button v-if="active==='笔试与面试'&&practiceTab==='interview'" class="primary" @click="interviewDialog=true" :disabled="applications.length===0">＋ 添加面试</button><button v-if="active==='笔试与面试'&&practiceTab==='notes'" class="primary" @click="experienceDialog=true">＋ 添加面经</button></div></div>
        <div v-if="active==='企业'" class="panel data-panel"><p v-if="companies.length===0" class="no-deadline">{{loading?'正在加载…':'尚无企业记录，请添加第一家企业。'}}</p><table v-else><thead><tr><th>企业名称</th><th>性质</th><th>地区</th><th>岗位数</th></tr></thead><tbody><tr v-for="c in companies" :key="c.id"><td><b>{{c.name}}</b><small v-if="c.shortName">{{c.shortName}}</small></td><td>{{c.nature||'—'}}</td><td>{{c.region||'—'}}</td><td>{{jobs.filter(j=>j.companyId===c.id).length}}</td></tr></tbody></table></div>
        <div v-else-if="active==='岗位'" class="panel data-panel"><p v-if="jobs.length===0" class="no-deadline">{{loading?'正在加载…':'尚无岗位，请先创建企业，再添加岗位。'}}</p><table v-else><thead><tr><th>岗位</th><th>企业</th><th>城市</th><th>截止日期</th><th>优先级</th><th>收藏</th><th>投递</th></tr></thead><tbody><tr v-for="j in jobs" :key="j.id"><td><b>{{j.title}}</b><small>{{j.department||j.jobNumber||'—'}}</small></td><td>{{j.companyName}}</td><td>{{j.city||'—'}}</td><td>{{j.deadline||'—'}}</td><td>{{j.priority}}</td><td><button class="table-action" :aria-label="j.favorite?'取消收藏':'收藏'" @click="toggleFavorite(j)">{{j.favorite?'♥':'♡'}}</button></td><td>{{applications.filter(a=>a.jobId===j.id).length}}</td></tr></tbody></table></div>
        <div v-else-if="active==='投递'" class="panel data-panel"><p v-if="applications.length===0" class="no-deadline">{{loading?'正在加载…':'尚无投递记录，可从岗位创建投递。'}}</p><table v-else><thead><tr><th>企业 · 岗位</th><th>投递时间</th><th>渠道</th><th>当前状态</th><th>历史</th></tr></thead><tbody><tr v-for="a in applications" :key="a.id"><td><b>{{a.companyName}}</b><small>{{a.jobTitle}}</small></td><td>{{a.appliedAt||'—'}}</td><td>{{a.channel||'—'}}</td><td><select :value="a.status" @change="changeStatus(a,$event)"><option v-for="s in ['已投递','简历筛选中','笔试待考','面试中','谈 Offer','主动放弃']" :key="s">{{s}}</option></select></td><td><button class="text-button" @click="viewHistory(a.id)">查看</button></td></tr></tbody></table></div>
        <div v-else-if="active==='简历与材料'" class="panel data-panel"><p v-if="resumes.length===0" class="no-deadline">尚无简历版本，添加元数据后可绑定到投递。</p><table v-else><thead><tr><th>版本名称</th><th>求职方向</th><th>版本号</th><th>文件</th></tr></thead><tbody><tr v-for="resume in resumes" :key="resume.id"><td><b>{{resume.name}}</b></td><td>{{resume.direction||'—'}}</td><td>{{resume.version||'—'}}</td><td><button v-if="resume.storedFileId" class="text-button" @click="downloadFile(resume.storedFileId)">下载附件</button><span v-else>—</span></td></tr></tbody></table></div>
        <div v-else-if="active==='笔试与面试'" class="panel practice-panel"><div class="practice-tabs"><button :class="{selected:practiceTab==='exam'}" @click="openPractice('exam')">笔试</button><button :class="{selected:practiceTab==='interview'}" @click="openPractice('interview')">面试</button><button :class="{selected:practiceTab==='notes'}" @click="openPractice('notes')">面经</button></div><div v-if="practiceTab==='exam'" class="data-panel"><p v-if="exams.length===0" class="no-deadline">暂无笔试安排</p><table v-else><thead><tr><th>平台</th><th>时间</th><th>成绩</th><th>结果</th><th>复盘</th></tr></thead><tbody><tr v-for="exam in exams" :key="exam.id"><td>{{exam.platform||'笔试'}}</td><td>{{exam.startsAt?new Date(exam.startsAt).toLocaleString():'—'}}</td><td>{{exam.score??'—'}}</td><td>{{exam.result||'—'}}</td><td>{{exam.reflection||'—'}}</td></tr></tbody></table></div><div v-else-if="practiceTab==='interview'" class="data-panel"><p v-if="interviews.length===0" class="no-deadline">暂无面试轮次，请先建立投递。</p><table v-else><thead><tr><th>企业 · 岗位</th><th>轮次</th><th>时间</th><th>形式</th><th>评分</th><th>结果</th><th>复盘</th></tr></thead><tbody><tr v-for="item in interviews" :key="item.id"><td>{{item.companyName}} · {{item.jobTitle}}</td><td>{{item.roundName}}</td><td>{{item.startsAt?new Date(item.startsAt).toLocaleString():'—'}}</td><td>{{item.modality||'—'}}</td><td>{{item.rating??'—'}}</td><td>{{item.result||'—'}}</td><td>{{item.review||'—'}}</td></tr></tbody></table></div><div v-else class="data-panel"><p v-if="experienceNotes.length===0" class="no-deadline">暂无面经</p><article v-for="note in experienceNotes" :key="note.id" class="experience-card"><b>{{note.companyName||'未关联企业'}} · {{note.title}}</b><small>{{note.roundName||'未标注轮次'}} · {{note.questions?.length||0}} 个问题 · 使用 {{note.usedCount}} 次</small><p>{{(note.questions||[]).join(' / ')}}</p></article></div></div>
        <div v-else-if="active==='个人资料'" class="panel profile-panel"><div class="profile-toolbar"><div class="profile-sections"><button v-for="section in profileSections" :key="section[0]" :class="{selected:profileSection===section[0]}" @click="chooseProfileSection(section[0])">{{section[1]}}</button></div><button class="primary" @click="profileDialog=true">＋ 添加资料</button></div><article v-for="entry in profileEntries" :key="entry.id" class="profile-entry"><h3>{{entry.title}}</h3><div class="profile-fields"><div v-for="(value,key) in entry.fields" :key="key" class="profile-field"><b>{{key}}</b><span>{{entry.visibleFields.includes(key)?value:'已隐藏'}}</span><button class="text-button" @click="toggleProfileVisibility(entry,key)">{{entry.visibleFields.includes(key)?'隐藏':'显示'}}</button><button v-if="entry.visibleFields.includes(key)" class="text-button" @click="copyValue(value)">复制</button></div></div></article><p v-if="profileEntries.length===0" class="no-deadline">暂无{{profileSections.find(s=>s[0]===profileSection)?.[1]}}记录。加密保存需要在服务器设置 APP_ENCRYPTION_KEY。</p></div>
        <div v-else-if="active==='日程'" class="panel calendar-panel"><div class="calendar-toolbar"><div class="calendar-modes"><button v-for="mode in calendarModes" :key="mode" :class="{selected:viewMode===mode}" @click="viewMode=mode;loadCalendar()">{{modeLabels[mode]}}</button></div><button class="outline" @click="cursorDate=new Date();loadCalendar()">今天</button><button class="round-add" @click="shiftCalendar(-1)">‹</button><b>{{calendarTitle}}</b><button class="round-add" @click="shiftCalendar(1)">›</button></div><div class="calendar-grid" :class="'mode-'+viewMode"><div class="calendar-day" v-for="d in calendarDays" :key="d.toISOString()" :class="{muted:viewMode==='month'&&d.getMonth()!==cursorDate.getMonth(),'is-today':dateKey(d)===dateKey(new Date())}"><b>{{d.toLocaleDateString('zh-CN',{weekday:'short'})}} {{d.getDate()}}</b><div v-for="event in eventsForDay(d)" :key="event.sourceType+event.id" class="calendar-event" :class="'event-'+event.sourceType.toLowerCase()">{{event.title}}</div></div></div><div class="task-list"><div class="panel-head"><div><h2>待办事项</h2><p>跨天展示并按完成状态筛选</p></div></div><label v-for="task in tasks" :key="task.id" class="task-row"><input type="checkbox" :checked="task.completed" @change="completeTask(task)"><span :class="{done:task.completed}">{{task.title}}</span><small>{{task.dueAt?new Date(task.dueAt).toLocaleString('zh-CN',{timeZone:task.timeZone||undefined}):'无截止时间'}}</small><i>{{task.priority}}</i></label><p v-if="tasks.length===0" class="no-deadline">暂无待办</p></div></div>
        <div v-else-if="active==='设置'" class="panel settings-panel"><h2>提醒与时区</h2><p>提醒在打开工作区时生成并显示为站内通知，不会尝试发送未配置的邮件或手机推送。</p><el-form label-position="top"><el-form-item label="截止日期提醒"><el-checkbox-group v-model="reminderDays"><el-checkbox v-for="day in [7,3,1,0]" :key="day" :label="day">{{day===0?'当天':`${day} 天前`}}</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="提醒时区（IANA）"><el-input v-model="reminderZone" placeholder="Asia/Shanghai" /></el-form-item></el-form><el-button type="primary" @click="saveReminderPreferences">保存提醒规则</el-button></div>
        <div v-else-if="active==='Offer'" class="panel data-panel"><div class="weight-editor"><b>Offer 比较权重（合计 100%）</b><div v-for="key in ['compensation','growth','role','location','culture']" :key="key"><label>{{comparisonLabels[key]}}</label><el-input-number v-model="comparisonWeights[key]" :min="0" :max="1" :step="0.05" :precision="2" /></div><el-button @click="saveComparisonWeights">保存权重</el-button></div><p v-if="offers.length===0" class="no-deadline">暂无 Offer，可先完成投递流程后记录。</p><table v-else><thead><tr><th>企业 · 岗位</th><th>月薪</th><th>奖金</th><th>股权</th><th>地点 / 形式</th><th>截止日期</th><th>加权分</th><th>决定</th></tr></thead><tbody><tr v-for="offer in offers" :key="offer.id"><td><b>{{offer.companyName}}</b><small>{{offer.jobTitle}}</small></td><td>{{offer.baseSalary??'—'}}</td><td>{{offer.bonus??'—'}}</td><td>{{offer.equity??'—'}}</td><td>{{offer.workCity||'—'}} / {{offer.workMode||'—'}}</td><td>{{offer.responseDeadline||'—'}}</td><td><b>{{offer.comparisonScore}}</b></td><td>{{offer.decision}}</td></tr></tbody></table></div>
        <div v-else-if="active==='数据分析'" class="panel data-panel"><h2>投递漏斗</h2><div class="analytics-grid"><article v-for="row in analytics.funnel" :key="row.stage"><b>{{row.stage}}</b><strong>{{row.count}}</strong></article></div><h2>按月投递</h2><p v-if="!analytics.monthlyApplications.length" class="no-deadline">暂无投递数据</p><div v-for="row in analytics.monthlyApplications" :key="row.month" class="analytics-row"><b>{{row.month}}</b><span>{{row.count}} 条申请</span></div><h2>投递渠道</h2><div v-for="(count,channel) in analytics.channels" :key="channel" class="analytics-row"><b>{{channel}}</b><span>{{count}} 条</span></div></div>
        <div v-else class="panel empty-state"><span>✳</span><b>{{active}}按路线图分阶段开放</b><p>此处不会用模拟数据代替真实业务功能。</p></div>
      </section>
    </main>
    <el-dialog v-model="offerDialog" title="记录 Offer" width="min(620px, 94vw)"><el-form label-position="top"><el-form-item label="对应投递" required><el-select v-model="offerDraft.applicationId"><el-option v-for="a in applications" :key="a.id" :label="`${a.companyName} · ${a.jobTitle}`" :value="a.id" /></el-select></el-form-item><el-form-item label="月薪"><el-input-number v-model="offerDraft.baseSalary" :min="0" /></el-form-item><el-form-item label="奖金"><el-input-number v-model="offerDraft.bonus" :min="0" /></el-form-item><el-form-item label="股权"><el-input-number v-model="offerDraft.equity" :min="0" /></el-form-item><el-form-item label="工作地点"><el-input v-model="offerDraft.workCity" /></el-form-item><el-form-item label="回复截止日期"><el-date-picker v-model="offerDraft.responseDeadline" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="决定"><el-select v-model="offerDraft.decision"><el-option v-for="d in ['待决定','已接受','已拒绝','已过期']" :key="d" :label="d" :value="d" /></el-select></el-form-item><el-form-item v-for="key in ['growth','role','location','culture']" :key="key" :label="key"><el-input-number v-model="offerDraft.evaluations[key]" :min="0" :max="100" /></el-form-item><el-form-item label="备注"><el-input v-model="offerDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="offerDialog=false">取消</el-button><el-button type="primary" :disabled="!offerDraft.applicationId" @click="createOffer">保存 Offer</el-button></template></el-dialog>\n    <el-dialog v-model="companyDialog" title="新建企业" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="企业名称" required><el-input v-model="companyDraft.name" /></el-form-item><el-form-item label="简称"><el-input v-model="companyDraft.shortName" /></el-form-item><el-form-item label="企业性质"><el-input v-model="companyDraft.nature" placeholder="民营、国企、外资等" /></el-form-item><el-form-item label="行业"><el-input v-model="companyDraft.industry" /></el-form-item><el-form-item label="地区"><el-input v-model="companyDraft.region" /></el-form-item><el-form-item label="招聘官网"><el-input v-model="companyDraft.recruitmentWebsite" /></el-form-item><el-form-item label="备注"><el-input v-model="companyDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="companyDialog=false">取消</el-button><el-button type="primary" :disabled="!companyDraft.name.trim()" @click="createCompany">保存企业</el-button></template></el-dialog>
    <el-dialog v-model="jobDialog" title="新建岗位" width="min(600px, 94vw)"><el-form label-position="top"><el-form-item label="所属企业" required><el-select v-model="jobDraft.companyId" placeholder="选择企业"><el-option v-for="c in companies" :key="c.id" :label="c.name" :value="c.id" /></el-select></el-form-item><el-form-item label="岗位名称" required><el-input v-model="jobDraft.title" /></el-form-item><el-form-item label="招聘批次"><el-input v-model="jobDraft.recruitmentType" /></el-form-item><el-form-item label="城市"><el-input v-model="jobDraft.city" /></el-form-item><el-form-item label="截止日期"><el-date-picker v-model="jobDraft.deadline" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="原始岗位编号"><el-input v-model="jobDraft.jobNumber" /></el-form-item><el-form-item label="岗位链接"><el-input v-model="jobDraft.sourceUrl" /></el-form-item><el-form-item label="备注"><el-input v-model="jobDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="jobDialog=false">取消</el-button><el-button type="primary" :disabled="!jobDraft.companyId||!jobDraft.title.trim()" @click="createJob">保存岗位</el-button></template></el-dialog>
    <el-dialog v-model="applicationDialog" title="新建投递" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="岗位" required><el-select v-model="applicationDraft.jobId" placeholder="选择岗位"><el-option v-for="j in jobs" :key="j.id" :label="`${j.companyName} · ${j.title}`" :value="j.id" /></el-select></el-form-item><el-form-item label="绑定简历版本"><el-select v-model="applicationDraft.resumeVersionId" clearable placeholder="可稍后补充"><el-option v-for="resume in resumes" :key="resume.id" :label="resume.name" :value="resume.id" /></el-select></el-form-item><el-form-item label="投递渠道"><el-input v-model="applicationDraft.channel" /></el-form-item><el-form-item label="平台账号（不含密码）"><el-input v-model="applicationDraft.platform" /></el-form-item><el-form-item label="内推人"><el-input v-model="applicationDraft.referrer" /></el-form-item><el-form-item label="备注"><el-input v-model="applicationDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="applicationDialog=false">取消</el-button><el-button type="primary" :disabled="!applicationDraft.jobId" @click="createApplication">保存投递</el-button></template></el-dialog>
    <el-dialog v-model="examDialog" title="添加笔试" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="绑定投递"><el-select v-model="examDraft.applicationId" clearable><el-option v-for="a in applications" :key="a.id" :label="`${a.companyName} · ${a.jobTitle}`" :value="a.id" /></el-select></el-form-item><el-form-item label="平台"><el-input v-model="examDraft.platform" /></el-form-item><el-form-item label="考试时间"><el-date-picker v-model="examDraft.startsAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-form-item label="考试链接"><el-input v-model="examDraft.examUrl" /></el-form-item><el-form-item label="准考证链接"><el-input v-model="examDraft.admissionUrl" /></el-form-item><el-form-item label="成绩"><el-input-number v-model="examDraft.score" :min="0" /></el-form-item><el-form-item label="结果"><el-input v-model="examDraft.result" /></el-form-item><el-form-item label="复盘"><el-input v-model="examDraft.reflection" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="examDialog=false">取消</el-button><el-button type="primary" @click="createExam">保存笔试</el-button></template></el-dialog>
    <el-dialog v-model="interviewDialog" title="添加面试轮次" width="min(600px, 94vw)"><el-form label-position="top"><el-form-item label="投递" required><el-select v-model="interviewDraft.applicationId"><el-option v-for="a in applications" :key="a.id" :label="`${a.companyName} · ${a.jobTitle}`" :value="a.id" /></el-select></el-form-item><el-form-item label="轮次" required><el-input v-model="interviewDraft.roundName" /></el-form-item><el-form-item label="时间"><el-date-picker v-model="interviewDraft.startsAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-form-item label="形式"><el-select v-model="interviewDraft.modality"><el-option v-for="x in ['线上','线下','电话','视频']" :key="x" :label="x" :value="x" /></el-select></el-form-item><el-form-item label="地点"><el-input v-model="interviewDraft.location" /></el-form-item><el-form-item label="面试官"><el-input v-model="interviewDraft.interviewer" /></el-form-item><el-form-item label="主观评分 1–10"><el-input-number v-model="interviewDraft.rating" :min="1" :max="10" /></el-form-item><el-form-item label="结果"><el-input v-model="interviewDraft.result" /></el-form-item><el-form-item label="复盘"><el-input v-model="interviewDraft.review" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="interviewDialog=false">取消</el-button><el-button type="primary" :disabled="!interviewDraft.applicationId" @click="createInterview">保存面试</el-button></template></el-dialog>
    <el-dialog v-model="experienceDialog" title="添加面经" width="min(600px, 94vw)"><el-form label-position="top"><el-form-item label="企业"><el-select v-model="experienceDraft.companyId" clearable><el-option v-for="c in companies" :key="c.id" :label="c.name" :value="c.id" /></el-select></el-form-item><el-form-item label="岗位"><el-select v-model="experienceDraft.jobId" clearable><el-option v-for="j in jobs" :key="j.id" :label="j.title" :value="j.id" /></el-select></el-form-item><el-form-item label="标题" required><el-input v-model="experienceDraft.title" /></el-form-item><el-form-item label="轮次"><el-input v-model="experienceDraft.roundName" /></el-form-item><el-form-item label="问题（每行一项）"><el-input v-model="experienceDraft.questions" type="textarea" /></el-form-item><el-form-item label="参考答案（每行一项）"><el-input v-model="experienceDraft.answers" type="textarea" /></el-form-item><el-form-item label="标签（逗号分隔）"><el-input v-model="experienceDraft.tags" /></el-form-item><el-form-item label="来源"><el-input v-model="experienceDraft.source" /></el-form-item></el-form><template #footer><el-button @click="experienceDialog=false">取消</el-button><el-button type="primary" :disabled="!experienceDraft.title.trim()" @click="createExperience">保存面经</el-button></template></el-dialog>
    <el-dialog v-model="resumeDialog" title="添加简历版本" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="版本名称" required><el-input v-model="resumeDraft.name" placeholder="如：后端研发校招版" /></el-form-item><el-form-item label="求职方向"><el-input v-model="resumeDraft.direction" /></el-form-item><el-form-item label="版本号"><el-input v-model="resumeDraft.version" /></el-form-item><el-form-item label="说明"><el-input v-model="resumeDraft.notes" type="textarea" /></el-form-item><el-form-item label="简历附件"><input aria-label="简历附件" type="file" accept=".pdf,.png,.jpg,.jpeg,application/pdf,image/png,image/jpeg" @change="attachResumeFile" /><small v-if="resumeDraft.storedFileId">附件已上传并绑定到版本</small></el-form-item></el-form><template #footer><el-button @click="resumeDialog=false">取消</el-button><el-button type="primary" :disabled="!resumeDraft.name.trim()" @click="createResume">保存版本</el-button></template></el-dialog>
    <el-dialog v-model="profileDialog" class="profile-dialog" title="添加加密个人资料" width="min(620px, 94vw)"><el-form label-position="top"><el-form-item label="资料分类"><el-select v-model="profileSection"><el-option v-for="s in profileSections" :key="s[0]" :label="s[1]" :value="s[0]" /></el-select></el-form-item><el-form-item label="条目名称"><el-input v-model="profileTitle" placeholder="如：本科教育经历" /></el-form-item><el-form-item label="字段，每行填写‘字段名=内容’" required><el-input v-model="profileFieldsText" type="textarea" :rows="8" placeholder="学校=
专业=
毕业时间=" /></el-form-item></el-form><template #footer><el-button @click="profileDialog=false">取消</el-button><el-button type="primary" :disabled="Object.keys(parseProfileFields()).length===0" @click="createProfile">加密保存</el-button></template></el-dialog>
    <el-dialog v-model="taskDialog" title="新建待办" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="事项" required><el-input v-model="taskDraft.title" placeholder="如：完成简历定制" /></el-form-item><el-form-item label="类型"><el-select v-model="taskDraft.taskType"><el-option v-for="v in ['投递','改简历','备材料','备笔试/面试','联系招聘者/内推人','其他']" :key="v" :label="v" :value="v" /></el-select></el-form-item><el-form-item label="截止时间"><el-date-picker v-model="taskDraft.dueAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-form-item label="关联岗位"><el-select v-model="taskDraft.jobId" clearable><el-option v-for="j in jobs" :key="j.id" :label="`${j.companyName} · ${j.title}`" :value="j.id" /></el-select></el-form-item></el-form><template #footer><el-button @click="taskDialog=false">取消</el-button><el-button type="primary" :disabled="!taskDraft.title.trim()" @click="createTask">保存待办</el-button></template></el-dialog>
    <el-dialog v-model="notificationDialog" title="站内提醒" width="min(560px, 94vw)"><div v-for="notification in notifications" :key="notification.id" class="notification-row"><span>{{notification.title}}</span><small>{{new Date(notification.dueAt).toLocaleString()}}</small><el-button v-if="!notification.readAt" link type="primary" @click="readNotification(notification)">标记已读</el-button></div><p v-if="notifications.length===0" class="no-deadline">暂无提醒</p></el-dialog>
  </div>
</template>
