<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from './api'
import { stableStage } from './workflow'
type Company = {id:string;name:string;shortName?:string;region?:string;nature?:string}
type Job = {id:string;companyId:string;companyName:string;title:string;city?:string;deadline?:string;favorite:boolean;priority:string}
type Application = {id:string;jobId:string;jobTitle:string;companyName:string;status:string;stage:string;appliedAt?:string}
type Resume = {id:string;name:string;direction?:string;version?:string}
type Task = {id:string;title:string;taskType:string;priority:string;dueAt?:string;timeZone?:string;completed:boolean;jobId?:string}
type CalendarEvent = {id:string;title:string;eventType:string;startsAt:string;endsAt?:string;sourceType:string;timeZone?:string}
type Notification = {id:string;title:string;dueAt:string;readAt?:string}
const active = ref('驾驶舱'), nav = ['驾驶舱','企业','岗位','投递','日程','简历与材料','个人资料','笔试与面试','Offer','数据分析','设置']
const companies=ref<Company[]>([]), jobs=ref<Job[]>([]), applications=ref<Application[]>([]), resumes=ref<Resume[]>([]), tasks=ref<Task[]>([]), calendarEvents=ref<CalendarEvent[]>([]), notifications=ref<Notification[]>([]), error=ref(''), loading=ref(true)
const companyDialog=ref(false),jobDialog=ref(false),applicationDialog=ref(false),resumeDialog=ref(false),taskDialog=ref(false),notificationDialog=ref(false)
const companyDraft=reactive({name:'',shortName:'',nature:'',industry:'',region:'',website:'',recruitmentWebsite:'',description:'',notes:''})
const resumeDraft=reactive({name:'',direction:'',version:'',notes:''})
const taskDraft=reactive({title:'',taskType:'其他',priority:'B',dueAt:'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,jobId:''})
const reminderDays=ref<number[]>([7,3,1,0]),reminderZone=ref(Intl.DateTimeFormat().resolvedOptions().timeZone)
const jobDraft=reactive({companyId:'',title:'',department:'',jobNumber:'',recruitmentType:'秋招',batch:'',city:'',degreeRequirement:'',majorRequirement:'',skillRequirement:'',salary:'',deadline:'',sourceUrl:'',notes:'',favorite:false,priority:'B'})
const applicationDraft=reactive({jobId:'',resumeVersionId:'',channel:'',platform:'',referrer:'',notes:'',status:'已投递',stage:'APPLICATION'})
const counts=computed(()=>({companies:companies.value.length,favorites:jobs.value.filter(j=>j.favorite).length,applied:applications.value.length,interviews:applications.value.filter(a=>a.stage==='INTERVIEW').length,offers:applications.value.filter(a=>a.stage==='OFFER').length}))
const unreadNotifications=computed(()=>notifications.value.filter(n=>!n.readAt).length)
const viewMode=ref<'month'|'week'|'day'>('week'),cursorDate=ref(new Date())
const calendarModes=['day','week','month'] as const,modeLabels:Record<'day'|'week'|'month',string>={day:'日',week:'周',month:'月'}
function dateKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function startOfWeek(d:Date){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());x.setDate(x.getDate()-(x.getDay()+6)%7);return x}
const calendarStart=computed(()=>viewMode.value==='day'?new Date(cursorDate.value.getFullYear(),cursorDate.value.getMonth(),cursorDate.value.getDate()):viewMode.value==='week'?startOfWeek(cursorDate.value):startOfWeek(new Date(cursorDate.value.getFullYear(),cursorDate.value.getMonth(),1)))
const calendarLength=computed(()=>viewMode.value==='day'?1:viewMode.value==='week'?7:42)
const calendarDays=computed(()=>Array.from({length:calendarLength.value},(_,i)=>{const d=new Date(calendarStart.value);d.setDate(d.getDate()+i);return d}))
const calendarTitle=computed(()=>viewMode.value==='day'?cursorDate.value.toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'}):viewMode.value==='week'?`${dateKey(calendarDays.value[0])} — ${dateKey(calendarDays.value[6])}`:cursorDate.value.toLocaleDateString('zh-CN',{year:'numeric',month:'long'}))
const todayTasks=computed(()=>{const k=dateKey(new Date());return tasks.value.filter(t=>!t.completed&&t.dueAt&&dateKey(new Date(t.dueAt))===k)})
const eventsForDay=(d:Date)=>calendarEvents.value.filter(e=>dateKey(new Date(e.startsAt))===dateKey(d))
async function loadCalendar(){const start=calendarStart.value,end=new Date(start);end.setDate(end.getDate()+calendarLength.value);try{calendarEvents.value=(await api.get('/calendar',{params:{from:start.toISOString(),to:end.toISOString()}})).data}catch{error.value='日历加载失败'}}
function shiftCalendar(direction:number){const d=new Date(cursorDate.value);if(viewMode.value==='month'){d.setDate(1);d.setMonth(d.getMonth()+direction)}else if(viewMode.value==='week')d.setDate(d.getDate()+7*direction);else d.setDate(d.getDate()+direction);cursorDate.value=d;void loadCalendar()}
async function openSection(item:string){active.value=item;if(item==='日程')await loadCalendar()}
async function load(){loading.value=true;error.value='';try{await api.get('/workspaces/current');[companies.value,jobs.value,applications.value,resumes.value,tasks.value]=await Promise.all([api.get('/companies').then(r=>r.data),api.get('/jobs').then(r=>r.data),api.get('/applications').then(r=>r.data),api.get('/resumes').then(r=>r.data),api.get('/tasks').then(r=>r.data)]);const prefs=(await api.get('/settings/reminders')).data;reminderDays.value=prefs.days;reminderZone.value=prefs.timeZone;await loadCalendar();await refreshNotifications()}catch(e:any){error.value=e?.response?.data?.title||'暂时无法加载工作区，请检查服务连接'}finally{loading.value=false}}
async function saveReminderPreferences(){try{const r=await api.put('/settings/reminders',{days:reminderDays.value,timeZone:reminderZone.value});reminderDays.value=r.data.days;reminderZone.value=r.data.timeZone;await refreshNotifications()}catch(e:any){error.value=e?.response?.data?.detail||'提醒规则保存失败'}}
async function createCompany(){try{await api.post('/companies',companyDraft);companyDialog.value=false;Object.assign(companyDraft,{name:'',shortName:'',nature:'',industry:'',region:'',website:'',recruitmentWebsite:'',description:'',notes:''});await load()}catch(e:any){error.value=e?.response?.data?.detail||'企业保存失败'}}
async function createResume(){try{await api.post('/resumes',resumeDraft);resumeDialog.value=false;Object.assign(resumeDraft,{name:'',direction:'',version:'',notes:''});await load()}catch(e:any){error.value=e?.response?.data?.detail||'简历版本保存失败'}}
async function createTask(){try{await api.post('/tasks',{title:taskDraft.title,taskType:taskDraft.taskType,priority:taskDraft.priority,timeZone:taskDraft.timeZone,dueAt:taskDraft.dueAt?new Date(taskDraft.dueAt).toISOString():null,jobId:taskDraft.jobId||null});taskDialog.value=false;Object.assign(taskDraft,{title:'',taskType:'其他',priority:'B',dueAt:'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,jobId:''});await load()}catch(e:any){error.value=e?.response?.data?.detail||'待办保存失败'}}
async function completeTask(task:Task){try{await api.put(`/tasks/${task.id}/complete`,{completed:!task.completed});await load()}catch{error.value='待办状态更新失败'}}
async function refreshNotifications(){try{notifications.value=(await api.get('/notifications')).data}catch{}}
async function showNotifications(){notificationDialog.value=true;await refreshNotifications()}
async function readNotification(item:Notification){try{await api.put(`/notifications/${item.id}/read`,{});notifications.value=notifications.value.map(n=>n.id===item.id?{...n,readAt:new Date().toISOString()}:n)}catch{error.value='提醒状态更新失败'}}
async function createJob(){try{await api.post('/jobs',{...jobDraft,deadline:jobDraft.deadline||null});jobDialog.value=false;Object.assign(jobDraft,{companyId:'',title:'',department:'',jobNumber:'',recruitmentType:'秋招',batch:'',city:'',degreeRequirement:'',majorRequirement:'',skillRequirement:'',salary:'',deadline:'',sourceUrl:'',notes:'',favorite:false,priority:'B'});await load()}catch(e:any){error.value=e?.response?.data?.detail||'岗位保存失败'}}
async function createApplication(){try{await api.post('/applications',{...applicationDraft,resumeVersionId:applicationDraft.resumeVersionId||null});applicationDialog.value=false;Object.assign(applicationDraft,{jobId:'',resumeVersionId:'',channel:'',platform:'',referrer:'',notes:'',status:'已投递',stage:'APPLICATION'});await load()}catch(e:any){error.value=e?.response?.data?.detail||'投递保存失败'}}
async function toggleFavorite(job:Job){try{await api.post(`/jobs/${job.id}/favorite`,{favorite:!job.favorite});await load()}catch(e:any){error.value='收藏状态更新失败'}}
async function changeStatus(item:Application,event:Event){const target=(event.target as HTMLSelectElement).value;if(!target)return;const stage=stableStage(target);if(!stage){error.value='此状态尚未配置阶段映射';return}try{await api.put(`/applications/${item.id}/status`,{status:target,stage,note:'工作台更新'});await load()}catch(e:any){error.value='状态更新失败'}}
async function viewHistory(id:string){try{const r=await api.get(`/applications/${id}/history`);window.alert(r.data.map((h:any)=>`${h.status} · ${h.changedAt}`).join('\n'))}catch{error.value='无法读取该投递的状态历史'}}
onMounted(load)
</script>

<template>
  <div class="shell">
    <aside class="sidebar"><div class="brand"><span class="brand-mark">H</span><div><b>Hire Cockpit</b><small>秋招工作台</small></div></div><div class="workspace"><span class="avatar">我</span><div><b>我的求职工作区</b><small>仅此浏览器可继续使用</small></div><span class="chevron">⌄</span></div><nav><button v-for="(item,i) in nav" :key="item" :class="{selected:active===item}" @click="openSection(item)"><span class="nav-icon">{{ ['⌂','▤','◈','↗','▦','▱','◉','✳','◇','▥','⚙'][i] }}</span>{{item}}</button></nav><div class="sidebar-bottom"><span class="online-dot"></span> 数据保存在安全工作区 <span class="help">?</span></div></aside>
    <main class="main"><header class="topbar"><div class="crumb">工作台 <span>/</span> {{active}}</div><div class="top-actions"><button class="search">⌕ <span>搜索企业、岗位、标签...</span><kbd>⌘ K</kbd></button><button class="icon-btn" aria-label="提醒" @click="showNotifications">♧<span v-if="unreadNotifications" class="notification-count">{{unreadNotifications}}</span></button><button class="user-chip"><span class="avatar">我</span> 我的工作区⌄</button></div></header>
      <section class="content" v-if="active==='驾驶舱'"><div class="welcome"><div><div class="eyebrow">HIRE COCKPIT <span class="sun">☼</span></div><h1>早上好，准备好开启新的一天了吗？</h1><p>每一步积累，都会让理想的机会离你更近。</p></div><button class="primary" @click="active='岗位'">＋ 添加新岗位</button></div>
        <div v-if="error" class="error-banner" role="alert">{{error}} <button @click="load">重试</button></div>
        <div class="stats"><article class="stat-card"><div class="stat-top"><span>已收藏岗位</span><span class="stat-icon lilac">♡</span></div><div class="stat-value">{{counts.favorites}} <small>个</small></div><div class="stat-note">来自当前浏览器工作区</div></article><article class="stat-card"><div class="stat-top"><span>已投递</span><span class="stat-icon blue">↗</span></div><div class="stat-value">{{counts.applied}} <small>个</small></div><div class="stat-note">所有申请，一目了然</div></article><article class="stat-card"><div class="stat-top"><span>面试进行中</span><span class="stat-icon amber">♧</span></div><div class="stat-value">{{counts.interviews}} <small>场</small></div><div class="stat-note">认真准备，从容应对</div></article><article class="stat-card"><div class="stat-top"><span>收获 Offer</span><span class="stat-icon green">◇</span></div><div class="stat-value">{{counts.offers}} <small>份</small></div><div class="stat-note">{{counts.companies}} 家企业记录</div></article></div>
        <div class="grid-main"><article class="panel pipeline"><div class="panel-head"><div><h2>求职进展</h2><p>从发现机会到收获 Offer</p></div><button class="text-button" @click="openSection('数据分析')">查看分析 →</button></div><div class="funnel-empty"><div class="funnel-art"><span>♡</span><span>↗</span><span>✳</span><span>◇</span></div><b v-if="applications.length===0">{{loading?'正在加载…':'你的求职故事，从这里开始'}}</b><b v-else>已记录 {{applications.length}} 条投递</b><p v-if="applications.length===0">添加第一个岗位，开启你的求职旅程</p><button class="outline" @click="openSection('岗位')">去添加岗位 →</button></div></article><article class="panel today"><div class="panel-head"><div><h2>今日安排</h2><p>{{todayTasks.length}} 项待办</p></div><button class="round-add" @click="openSection('日程')">＋</button></div><div v-if="todayTasks.length" class="today-list"><label v-for="task in todayTasks" :key="task.id"><input type="checkbox" :checked="task.completed" @change="completeTask(task)"><span>{{task.title}}</span><small>{{new Date(task.dueAt!).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></label></div><div v-else class="empty-task"><span>☼</span><b>{{loading?'正在加载…':'今天还没有待办'}}</b><p>给自己定个小目标吧</p><button class="text-button" @click="openSection('日程')">＋ 创建任务</button></div></article></div>
        <div class="bottom-grid"><article class="panel deadlines"><div class="panel-head"><div><h2>近期截止</h2><p>别错过重要的时间节点</p></div><button class="text-button" @click="active='岗位'">全部岗位 →</button></div><div class="no-deadline">{{jobs.filter(j=>j.deadline).length?jobs.filter(j=>j.deadline).map(j=>`${j.title} · ${j.deadline}`).join('　'): '暂无即将截止的事项'}}</div></article><article class="tip"><span class="tip-spark">✦</span><div><small>工作区安全提示</small><p>清除 Cookie 或更换设备前，请先导出数据备份。</p><button @click="active='设置'">了解数据管理 →</button></div><span class="tip-orb"></span></article></div><footer>© 2026 Hire Cockpit <span>用心规划，静待花开 <b>✳</b></span></footer>
      </section>
      <section v-else class="content placeholder"><div class="welcome"><div><div class="eyebrow">HIRE COCKPIT · {{active}}</div><h1>{{active}}</h1><p>{{error||'管理你的求职信息与进展。'}}</p></div><div class="toolbar"><button v-if="active==='企业'" class="primary" @click="companyDialog=true">＋ 新建企业</button><button v-if="active==='岗位'" class="primary" @click="jobDialog=true" :disabled="companies.length===0">＋ 新建岗位</button><button v-if="active==='投递'" class="primary" @click="applicationDialog=true" :disabled="jobs.length===0">＋ 新建投递</button><button v-if="active==='简历与材料'" class="primary" @click="resumeDialog=true">＋ 添加简历版本</button><button v-if="active==='日程'" class="primary" @click="taskDialog=true">＋ 新建待办</button></div></div>
        <div v-if="active==='企业'" class="panel data-panel"><p v-if="companies.length===0" class="no-deadline">{{loading?'正在加载…':'尚无企业记录，请添加第一家企业。'}}</p><table v-else><thead><tr><th>企业名称</th><th>性质</th><th>地区</th><th>岗位数</th></tr></thead><tbody><tr v-for="c in companies" :key="c.id"><td><b>{{c.name}}</b><small v-if="c.shortName">{{c.shortName}}</small></td><td>{{c.nature||'—'}}</td><td>{{c.region||'—'}}</td><td>{{jobs.filter(j=>j.companyId===c.id).length}}</td></tr></tbody></table></div>
        <div v-else-if="active==='岗位'" class="panel data-panel"><p v-if="jobs.length===0" class="no-deadline">{{loading?'正在加载…':'尚无岗位，请先创建企业，再添加岗位。'}}</p><table v-else><thead><tr><th>岗位</th><th>企业</th><th>城市</th><th>截止日期</th><th>优先级</th><th>收藏</th><th>投递</th></tr></thead><tbody><tr v-for="j in jobs" :key="j.id"><td><b>{{j.title}}</b><small>{{j.department||j.jobNumber||'—'}}</small></td><td>{{j.companyName}}</td><td>{{j.city||'—'}}</td><td>{{j.deadline||'—'}}</td><td>{{j.priority}}</td><td><button class="table-action" :aria-label="j.favorite?'取消收藏':'收藏'" @click="toggleFavorite(j)">{{j.favorite?'♥':'♡'}}</button></td><td>{{applications.filter(a=>a.jobId===j.id).length}}</td></tr></tbody></table></div>
        <div v-else-if="active==='投递'" class="panel data-panel"><p v-if="applications.length===0" class="no-deadline">{{loading?'正在加载…':'尚无投递记录，可从岗位创建投递。'}}</p><table v-else><thead><tr><th>企业 · 岗位</th><th>投递时间</th><th>渠道</th><th>当前状态</th><th>历史</th></tr></thead><tbody><tr v-for="a in applications" :key="a.id"><td><b>{{a.companyName}}</b><small>{{a.jobTitle}}</small></td><td>{{a.appliedAt||'—'}}</td><td>{{a.channel||'—'}}</td><td><select :value="a.status" @change="changeStatus(a,$event)"><option v-for="s in ['已投递','简历筛选中','笔试待考','面试中','谈 Offer','主动放弃']" :key="s">{{s}}</option></select></td><td><button class="text-button" @click="viewHistory(a.id)">查看</button></td></tr></tbody></table></div>
        <div v-else-if="active==='简历与材料'" class="panel data-panel"><p v-if="resumes.length===0" class="no-deadline">尚无简历版本，添加元数据后可绑定到投递。</p><table v-else><thead><tr><th>版本名称</th><th>求职方向</th><th>版本号</th></tr></thead><tbody><tr v-for="resume in resumes" :key="resume.id"><td><b>{{resume.name}}</b></td><td>{{resume.direction||'—'}}</td><td>{{resume.version||'—'}}</td></tr></tbody></table></div>
        <div v-else-if="active==='日程'" class="panel calendar-panel"><div class="calendar-toolbar"><div class="calendar-modes"><button v-for="mode in calendarModes" :key="mode" :class="{selected:viewMode===mode}" @click="viewMode=mode;loadCalendar()">{{modeLabels[mode]}}</button></div><button class="outline" @click="cursorDate=new Date();loadCalendar()">今天</button><button class="round-add" @click="shiftCalendar(-1)">‹</button><b>{{calendarTitle}}</b><button class="round-add" @click="shiftCalendar(1)">›</button></div><div class="calendar-grid" :class="'mode-'+viewMode"><div class="calendar-day" v-for="d in calendarDays" :key="d.toISOString()" :class="{muted:viewMode==='month'&&d.getMonth()!==cursorDate.getMonth(),'is-today':dateKey(d)===dateKey(new Date())}"><b>{{d.toLocaleDateString('zh-CN',{weekday:'short'})}} {{d.getDate()}}</b><div v-for="event in eventsForDay(d)" :key="event.sourceType+event.id" class="calendar-event" :class="'event-'+event.sourceType.toLowerCase()">{{event.title}}</div></div></div><div class="task-list"><div class="panel-head"><div><h2>待办事项</h2><p>跨天展示并按完成状态筛选</p></div></div><label v-for="task in tasks" :key="task.id" class="task-row"><input type="checkbox" :checked="task.completed" @change="completeTask(task)"><span :class="{done:task.completed}">{{task.title}}</span><small>{{task.dueAt?new Date(task.dueAt).toLocaleString('zh-CN',{timeZone:task.timeZone||undefined}):'无截止时间'}}</small><i>{{task.priority}}</i></label><p v-if="tasks.length===0" class="no-deadline">暂无待办</p></div></div>
        <div v-else-if="active==='设置'" class="panel settings-panel"><h2>提醒与时区</h2><p>提醒在打开工作区时生成并显示为站内通知，不会尝试发送未配置的邮件或手机推送。</p><el-form label-position="top"><el-form-item label="截止日期提醒"><el-checkbox-group v-model="reminderDays"><el-checkbox v-for="day in [7,3,1,0]" :key="day" :label="day">{{day===0?'当天':`${day} 天前`}}</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="提醒时区（IANA）"><el-input v-model="reminderZone" placeholder="Asia/Shanghai" /></el-form-item></el-form><el-button type="primary" @click="saveReminderPreferences">保存提醒规则</el-button></div>
        <div v-else class="panel empty-state"><span>✳</span><b>{{active}}按路线图分阶段开放</b><p>此处不会用模拟数据代替真实业务功能。</p></div>
      </section>
    </main>
    <el-dialog v-model="companyDialog" title="新建企业" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="企业名称" required><el-input v-model="companyDraft.name" /></el-form-item><el-form-item label="简称"><el-input v-model="companyDraft.shortName" /></el-form-item><el-form-item label="企业性质"><el-input v-model="companyDraft.nature" placeholder="民营、国企、外资等" /></el-form-item><el-form-item label="行业"><el-input v-model="companyDraft.industry" /></el-form-item><el-form-item label="地区"><el-input v-model="companyDraft.region" /></el-form-item><el-form-item label="招聘官网"><el-input v-model="companyDraft.recruitmentWebsite" /></el-form-item><el-form-item label="备注"><el-input v-model="companyDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="companyDialog=false">取消</el-button><el-button type="primary" :disabled="!companyDraft.name.trim()" @click="createCompany">保存企业</el-button></template></el-dialog>
    <el-dialog v-model="jobDialog" title="新建岗位" width="min(600px, 94vw)"><el-form label-position="top"><el-form-item label="所属企业" required><el-select v-model="jobDraft.companyId" placeholder="选择企业"><el-option v-for="c in companies" :key="c.id" :label="c.name" :value="c.id" /></el-select></el-form-item><el-form-item label="岗位名称" required><el-input v-model="jobDraft.title" /></el-form-item><el-form-item label="招聘批次"><el-input v-model="jobDraft.recruitmentType" /></el-form-item><el-form-item label="城市"><el-input v-model="jobDraft.city" /></el-form-item><el-form-item label="截止日期"><el-date-picker v-model="jobDraft.deadline" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="原始岗位编号"><el-input v-model="jobDraft.jobNumber" /></el-form-item><el-form-item label="岗位链接"><el-input v-model="jobDraft.sourceUrl" /></el-form-item><el-form-item label="备注"><el-input v-model="jobDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="jobDialog=false">取消</el-button><el-button type="primary" :disabled="!jobDraft.companyId||!jobDraft.title.trim()" @click="createJob">保存岗位</el-button></template></el-dialog>
    <el-dialog v-model="applicationDialog" title="新建投递" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="岗位" required><el-select v-model="applicationDraft.jobId" placeholder="选择岗位"><el-option v-for="j in jobs" :key="j.id" :label="`${j.companyName} · ${j.title}`" :value="j.id" /></el-select></el-form-item><el-form-item label="绑定简历版本"><el-select v-model="applicationDraft.resumeVersionId" clearable placeholder="可稍后补充"><el-option v-for="resume in resumes" :key="resume.id" :label="resume.name" :value="resume.id" /></el-select></el-form-item><el-form-item label="投递渠道"><el-input v-model="applicationDraft.channel" /></el-form-item><el-form-item label="平台账号（不含密码）"><el-input v-model="applicationDraft.platform" /></el-form-item><el-form-item label="内推人"><el-input v-model="applicationDraft.referrer" /></el-form-item><el-form-item label="备注"><el-input v-model="applicationDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="applicationDialog=false">取消</el-button><el-button type="primary" :disabled="!applicationDraft.jobId" @click="createApplication">保存投递</el-button></template></el-dialog>
    <el-dialog v-model="resumeDialog" title="添加简历版本" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="版本名称" required><el-input v-model="resumeDraft.name" placeholder="如：后端研发校招版" /></el-form-item><el-form-item label="求职方向"><el-input v-model="resumeDraft.direction" /></el-form-item><el-form-item label="版本号"><el-input v-model="resumeDraft.version" /></el-form-item><el-form-item label="说明"><el-input v-model="resumeDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="resumeDialog=false">取消</el-button><el-button type="primary" :disabled="!resumeDraft.name.trim()" @click="createResume">保存版本</el-button></template></el-dialog>
    <el-dialog v-model="taskDialog" title="新建待办" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="事项" required><el-input v-model="taskDraft.title" placeholder="如：完成简历定制" /></el-form-item><el-form-item label="类型"><el-select v-model="taskDraft.taskType"><el-option v-for="v in ['投递','改简历','备材料','备笔试/面试','联系招聘者/内推人','其他']" :key="v" :label="v" :value="v" /></el-select></el-form-item><el-form-item label="截止时间"><el-date-picker v-model="taskDraft.dueAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" /></el-form-item><el-form-item label="关联岗位"><el-select v-model="taskDraft.jobId" clearable><el-option v-for="j in jobs" :key="j.id" :label="`${j.companyName} · ${j.title}`" :value="j.id" /></el-select></el-form-item></el-form><template #footer><el-button @click="taskDialog=false">取消</el-button><el-button type="primary" :disabled="!taskDraft.title.trim()" @click="createTask">保存待办</el-button></template></el-dialog>
    <el-dialog v-model="notificationDialog" title="站内提醒" width="min(560px, 94vw)"><div v-for="notification in notifications" :key="notification.id" class="notification-row"><span>{{notification.title}}</span><small>{{new Date(notification.dueAt).toLocaleString()}}</small><el-button v-if="!notification.readAt" link type="primary" @click="readNotification(notification)">标记已读</el-button></div><p v-if="notifications.length===0" class="no-deadline">暂无提醒</p></el-dialog>
  </div>
</template>
