<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from './api'
import { stableStage } from './workflow'
type Company = {id:string;name:string;shortName?:string;region?:string;nature?:string}
type Job = {id:string;companyId:string;companyName:string;title:string;city?:string;deadline?:string;favorite:boolean;priority:string}
type Application = {id:string;jobId:string;jobTitle:string;companyName:string;status:string;stage:string;appliedAt?:string}
type Resume = {id:string;name:string;direction?:string;version?:string}
const active = ref('驾驶舱'), nav = ['驾驶舱','企业','岗位','投递','日程','简历与材料','个人资料','笔试与面试','Offer','数据分析','设置']
const companies=ref<Company[]>([]), jobs=ref<Job[]>([]), applications=ref<Application[]>([]), resumes=ref<Resume[]>([]), error=ref(''), loading=ref(true)
const companyDialog=ref(false),jobDialog=ref(false),applicationDialog=ref(false),resumeDialog=ref(false)
const companyDraft=reactive({name:'',shortName:'',nature:'',industry:'',region:'',website:'',recruitmentWebsite:'',description:'',notes:''})
const resumeDraft=reactive({name:'',direction:'',version:'',notes:''})
const jobDraft=reactive({companyId:'',title:'',department:'',jobNumber:'',recruitmentType:'秋招',batch:'',city:'',degreeRequirement:'',majorRequirement:'',skillRequirement:'',salary:'',deadline:'',sourceUrl:'',notes:'',favorite:false,priority:'B'})
const applicationDraft=reactive({jobId:'',resumeVersionId:'',channel:'',platform:'',referrer:'',notes:'',status:'已投递',stage:'APPLICATION'})
const counts=computed(()=>({companies:companies.value.length,favorites:jobs.value.filter(j=>j.favorite).length,applied:applications.value.length,interviews:applications.value.filter(a=>a.stage==='INTERVIEW').length,offers:applications.value.filter(a=>a.stage==='OFFER').length}))
async function load(){loading.value=true;error.value='';try{await api.get('/workspaces/current');[companies.value,jobs.value,applications.value,resumes.value]=await Promise.all([api.get('/companies').then(r=>r.data),api.get('/jobs').then(r=>r.data),api.get('/applications').then(r=>r.data),api.get('/resumes').then(r=>r.data)])}catch(e:any){error.value=e?.response?.data?.title||'暂时无法加载工作区，请检查服务连接'}finally{loading.value=false}}
async function createCompany(){try{await api.post('/companies',companyDraft);companyDialog.value=false;Object.assign(companyDraft,{name:'',shortName:'',nature:'',industry:'',region:'',website:'',recruitmentWebsite:'',description:'',notes:''});await load()}catch(e:any){error.value=e?.response?.data?.detail||'企业保存失败'}}
async function createResume(){try{await api.post('/resumes',resumeDraft);resumeDialog.value=false;Object.assign(resumeDraft,{name:'',direction:'',version:'',notes:''});await load()}catch(e:any){error.value=e?.response?.data?.detail||'简历版本保存失败'}}
async function createJob(){try{await api.post('/jobs',{...jobDraft,deadline:jobDraft.deadline||null});jobDialog.value=false;Object.assign(jobDraft,{companyId:'',title:'',department:'',jobNumber:'',recruitmentType:'秋招',batch:'',city:'',degreeRequirement:'',majorRequirement:'',skillRequirement:'',salary:'',deadline:'',sourceUrl:'',notes:'',favorite:false,priority:'B'});await load()}catch(e:any){error.value=e?.response?.data?.detail||'岗位保存失败'}}
async function createApplication(){try{await api.post('/applications',{...applicationDraft,resumeVersionId:applicationDraft.resumeVersionId||null});applicationDialog.value=false;Object.assign(applicationDraft,{jobId:'',resumeVersionId:'',channel:'',platform:'',referrer:'',notes:'',status:'已投递',stage:'APPLICATION'});await load()}catch(e:any){error.value=e?.response?.data?.detail||'投递保存失败'}}
async function toggleFavorite(job:Job){try{await api.post(`/jobs/${job.id}/favorite`,{favorite:!job.favorite});await load()}catch(e:any){error.value='收藏状态更新失败'}}
async function changeStatus(item:Application,event:Event){const target=(event.target as HTMLSelectElement).value;if(!target)return;const stage=stableStage(target);if(!stage){error.value='此状态尚未配置阶段映射';return}try{await api.put(`/applications/${item.id}/status`,{status:target,stage,note:'工作台更新'});await load()}catch(e:any){error.value='状态更新失败'}}
async function viewHistory(id:string){try{const r=await api.get(`/applications/${id}/history`);window.alert(r.data.map((h:any)=>`${h.status} · ${h.changedAt}`).join('\n'))}catch{error.value='无法读取该投递的状态历史'}}
onMounted(load)
</script>

<template>
  <div class="shell">
    <aside class="sidebar"><div class="brand"><span class="brand-mark">H</span><div><b>Hire Cockpit</b><small>秋招工作台</small></div></div><div class="workspace"><span class="avatar">我</span><div><b>我的求职工作区</b><small>仅此浏览器可继续使用</small></div><span class="chevron">⌄</span></div><nav><button v-for="(item,i) in nav" :key="item" :class="{selected:active===item}" @click="active=item"><span class="nav-icon">{{ ['⌂','▤','◈','↗','▦','▱','◉','✳','◇','▥','⚙'][i] }}</span>{{item}}</button></nav><div class="sidebar-bottom"><span class="online-dot"></span> 数据保存在安全工作区 <span class="help">?</span></div></aside>
    <main class="main"><header class="topbar"><div class="crumb">工作台 <span>/</span> {{active}}</div><div class="top-actions"><button class="search">⌕ <span>搜索企业、岗位、标签...</span><kbd>⌘ K</kbd></button><button class="icon-btn" aria-label="提醒">♧</button><button class="user-chip"><span class="avatar">我</span> 我的工作区⌄</button></div></header>
      <section class="content" v-if="active==='驾驶舱'"><div class="welcome"><div><div class="eyebrow">HIRE COCKPIT <span class="sun">☼</span></div><h1>早上好，准备好开启新的一天了吗？</h1><p>每一步积累，都会让理想的机会离你更近。</p></div><button class="primary" @click="active='岗位'">＋ 添加新岗位</button></div>
        <div v-if="error" class="error-banner" role="alert">{{error}} <button @click="load">重试</button></div>
        <div class="stats"><article class="stat-card"><div class="stat-top"><span>已收藏岗位</span><span class="stat-icon lilac">♡</span></div><div class="stat-value">{{counts.favorites}} <small>个</small></div><div class="stat-note">来自当前浏览器工作区</div></article><article class="stat-card"><div class="stat-top"><span>已投递</span><span class="stat-icon blue">↗</span></div><div class="stat-value">{{counts.applied}} <small>个</small></div><div class="stat-note">所有申请，一目了然</div></article><article class="stat-card"><div class="stat-top"><span>面试进行中</span><span class="stat-icon amber">♧</span></div><div class="stat-value">{{counts.interviews}} <small>场</small></div><div class="stat-note">认真准备，从容应对</div></article><article class="stat-card"><div class="stat-top"><span>收获 Offer</span><span class="stat-icon green">◇</span></div><div class="stat-value">{{counts.offers}} <small>份</small></div><div class="stat-note">{{counts.companies}} 家企业记录</div></article></div>
        <div class="grid-main"><article class="panel pipeline"><div class="panel-head"><div><h2>求职进展</h2><p>从发现机会到收获 Offer</p></div><button class="text-button" @click="active='数据分析'">查看分析 →</button></div><div class="funnel-empty"><div class="funnel-art"><span>♡</span><span>↗</span><span>✳</span><span>◇</span></div><b v-if="applications.length===0">{{loading?'正在加载…':'你的求职故事，从这里开始'}}</b><b v-else>已记录 {{applications.length}} 条投递</b><p v-if="applications.length===0">添加第一个岗位，开启你的求职旅程</p><button class="outline" @click="active='岗位'">去添加岗位 →</button></div></article><article class="panel today"><div class="panel-head"><div><h2>今日安排</h2><p>日程与待办</p></div><button class="round-add" @click="active='日程'">＋</button></div><div class="empty-task"><span>☼</span><b>日程模块将在 S2 开放</b><p>企业、岗位和投递已可开始记录</p><button class="text-button" @click="active='企业'">管理企业 →</button></div></article></div>
        <div class="bottom-grid"><article class="panel deadlines"><div class="panel-head"><div><h2>近期截止</h2><p>别错过重要的时间节点</p></div><button class="text-button" @click="active='岗位'">全部岗位 →</button></div><div class="no-deadline">{{jobs.filter(j=>j.deadline).length?jobs.filter(j=>j.deadline).map(j=>`${j.title} · ${j.deadline}`).join('　'): '暂无即将截止的事项'}}</div></article><article class="tip"><span class="tip-spark">✦</span><div><small>工作区安全提示</small><p>清除 Cookie 或更换设备前，请先导出数据备份。</p><button @click="active='设置'">了解数据管理 →</button></div><span class="tip-orb"></span></article></div><footer>© 2026 Hire Cockpit <span>用心规划，静待花开 <b>✳</b></span></footer>
      </section>
      <section v-else class="content placeholder"><div class="welcome"><div><div class="eyebrow">HIRE COCKPIT · {{active}}</div><h1>{{active}}</h1><p>{{error||'管理你的求职信息与进展。'}}</p></div><div class="toolbar"><button v-if="active==='企业'" class="primary" @click="companyDialog=true">＋ 新建企业</button><button v-if="active==='岗位'" class="primary" @click="jobDialog=true" :disabled="companies.length===0">＋ 新建岗位</button><button v-if="active==='投递'" class="primary" @click="applicationDialog=true" :disabled="jobs.length===0">＋ 新建投递</button><button v-if="active==='简历与材料'" class="primary" @click="resumeDialog=true">＋ 添加简历版本</button></div></div>
        <div v-if="active==='企业'" class="panel data-panel"><p v-if="companies.length===0" class="no-deadline">{{loading?'正在加载…':'尚无企业记录，请添加第一家企业。'}}</p><table v-else><thead><tr><th>企业名称</th><th>性质</th><th>地区</th><th>岗位数</th></tr></thead><tbody><tr v-for="c in companies" :key="c.id"><td><b>{{c.name}}</b><small v-if="c.shortName">{{c.shortName}}</small></td><td>{{c.nature||'—'}}</td><td>{{c.region||'—'}}</td><td>{{jobs.filter(j=>j.companyId===c.id).length}}</td></tr></tbody></table></div>
        <div v-else-if="active==='岗位'" class="panel data-panel"><p v-if="jobs.length===0" class="no-deadline">{{loading?'正在加载…':'尚无岗位，请先创建企业，再添加岗位。'}}</p><table v-else><thead><tr><th>岗位</th><th>企业</th><th>城市</th><th>截止日期</th><th>优先级</th><th>收藏</th><th>投递</th></tr></thead><tbody><tr v-for="j in jobs" :key="j.id"><td><b>{{j.title}}</b><small>{{j.department||j.jobNumber||'—'}}</small></td><td>{{j.companyName}}</td><td>{{j.city||'—'}}</td><td>{{j.deadline||'—'}}</td><td>{{j.priority}}</td><td><button class="table-action" :aria-label="j.favorite?'取消收藏':'收藏'" @click="toggleFavorite(j)">{{j.favorite?'♥':'♡'}}</button></td><td>{{applications.filter(a=>a.jobId===j.id).length}}</td></tr></tbody></table></div>
        <div v-else-if="active==='投递'" class="panel data-panel"><p v-if="applications.length===0" class="no-deadline">{{loading?'正在加载…':'尚无投递记录，可从岗位创建投递。'}}</p><table v-else><thead><tr><th>企业 · 岗位</th><th>投递时间</th><th>渠道</th><th>当前状态</th><th>历史</th></tr></thead><tbody><tr v-for="a in applications" :key="a.id"><td><b>{{a.companyName}}</b><small>{{a.jobTitle}}</small></td><td>{{a.appliedAt||'—'}}</td><td>{{a.channel||'—'}}</td><td><select :value="a.status" @change="changeStatus(a,$event)"><option v-for="s in ['已投递','简历筛选中','笔试待考','面试中','谈 Offer','主动放弃']" :key="s">{{s}}</option></select></td><td><button class="text-button" @click="viewHistory(a.id)">查看</button></td></tr></tbody></table></div>
        <div v-else-if="active==='简历与材料'" class="panel data-panel"><p v-if="resumes.length===0" class="no-deadline">尚无简历版本，添加元数据后可绑定到投递。</p><table v-else><thead><tr><th>版本名称</th><th>求职方向</th><th>版本号</th></tr></thead><tbody><tr v-for="resume in resumes" :key="resume.id"><td><b>{{resume.name}}</b></td><td>{{resume.direction||'—'}}</td><td>{{resume.version||'—'}}</td></tr></tbody></table></div>
        <div v-else class="panel empty-state"><span>✳</span><b>{{active}}按路线图分阶段开放</b><p>此处不会用模拟数据代替真实业务功能。</p></div>
      </section>
    </main>
    <el-dialog v-model="companyDialog" title="新建企业" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="企业名称" required><el-input v-model="companyDraft.name" /></el-form-item><el-form-item label="简称"><el-input v-model="companyDraft.shortName" /></el-form-item><el-form-item label="企业性质"><el-input v-model="companyDraft.nature" placeholder="民营、国企、外资等" /></el-form-item><el-form-item label="行业"><el-input v-model="companyDraft.industry" /></el-form-item><el-form-item label="地区"><el-input v-model="companyDraft.region" /></el-form-item><el-form-item label="招聘官网"><el-input v-model="companyDraft.recruitmentWebsite" /></el-form-item><el-form-item label="备注"><el-input v-model="companyDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="companyDialog=false">取消</el-button><el-button type="primary" :disabled="!companyDraft.name.trim()" @click="createCompany">保存企业</el-button></template></el-dialog>
    <el-dialog v-model="jobDialog" title="新建岗位" width="min(600px, 94vw)"><el-form label-position="top"><el-form-item label="所属企业" required><el-select v-model="jobDraft.companyId" placeholder="选择企业"><el-option v-for="c in companies" :key="c.id" :label="c.name" :value="c.id" /></el-select></el-form-item><el-form-item label="岗位名称" required><el-input v-model="jobDraft.title" /></el-form-item><el-form-item label="招聘批次"><el-input v-model="jobDraft.recruitmentType" /></el-form-item><el-form-item label="城市"><el-input v-model="jobDraft.city" /></el-form-item><el-form-item label="截止日期"><el-date-picker v-model="jobDraft.deadline" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="原始岗位编号"><el-input v-model="jobDraft.jobNumber" /></el-form-item><el-form-item label="岗位链接"><el-input v-model="jobDraft.sourceUrl" /></el-form-item><el-form-item label="备注"><el-input v-model="jobDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="jobDialog=false">取消</el-button><el-button type="primary" :disabled="!jobDraft.companyId||!jobDraft.title.trim()" @click="createJob">保存岗位</el-button></template></el-dialog>
    <el-dialog v-model="applicationDialog" title="新建投递" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="岗位" required><el-select v-model="applicationDraft.jobId" placeholder="选择岗位"><el-option v-for="j in jobs" :key="j.id" :label="`${j.companyName} · ${j.title}`" :value="j.id" /></el-select></el-form-item><el-form-item label="绑定简历版本"><el-select v-model="applicationDraft.resumeVersionId" clearable placeholder="可稍后补充"><el-option v-for="resume in resumes" :key="resume.id" :label="resume.name" :value="resume.id" /></el-select></el-form-item><el-form-item label="投递渠道"><el-input v-model="applicationDraft.channel" /></el-form-item><el-form-item label="平台账号（不含密码）"><el-input v-model="applicationDraft.platform" /></el-form-item><el-form-item label="内推人"><el-input v-model="applicationDraft.referrer" /></el-form-item><el-form-item label="备注"><el-input v-model="applicationDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="applicationDialog=false">取消</el-button><el-button type="primary" :disabled="!applicationDraft.jobId" @click="createApplication">保存投递</el-button></template></el-dialog>
    <el-dialog v-model="resumeDialog" title="添加简历版本" width="min(560px, 94vw)"><el-form label-position="top"><el-form-item label="版本名称" required><el-input v-model="resumeDraft.name" placeholder="如：后端研发校招版" /></el-form-item><el-form-item label="求职方向"><el-input v-model="resumeDraft.direction" /></el-form-item><el-form-item label="版本号"><el-input v-model="resumeDraft.version" /></el-form-item><el-form-item label="说明"><el-input v-model="resumeDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="resumeDialog=false">取消</el-button><el-button type="primary" :disabled="!resumeDraft.name.trim()" @click="createResume">保存版本</el-button></template></el-dialog>
  </div>
</template>
