import { test, expect, type Page } from '@playwright/test'

async function openSelect(page: Page, label: string) {
  await page.locator('.el-form-item').filter({ hasText: label }).locator('.el-select__wrapper').click()
}

test('production PWA manifest, service worker and offline shell', async ({ page, context }) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') pageErrors.push(message.text()) })
  page.on('requestfailed', request => pageErrors.push(`${request.url()}: ${request.failure()?.errorText}`))
  await page.goto('/')
  await page.evaluate(() => navigator.serviceWorker.ready)
  const pwa = await page.evaluate(async () => {
    const manifestLink = document.querySelector<HTMLLinkElement>('link[rel="manifest"]')!
    const manifest = await fetch(manifestLink.href).then(r => r.json())
    const registrations = await navigator.serviceWorker.getRegistrations()
    return { display: manifest.display, iconSizes: manifest.icons.map((icon: { sizes: string }) => icon.sizes), activeWorkers: registrations.filter(r => !!r.active).length }
  })
  expect(pwa.display).toBe('standalone')
  expect(pwa.iconSizes).toContain('192x192')
  expect(pwa.iconSizes).toContain('512x512')
  expect(pwa.activeWorkers).toBeGreaterThan(0)
  if (!await page.evaluate(() => Boolean(navigator.serviceWorker.controller))) await page.reload()
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  await context.setOffline(true)
  await page.reload()
  const heading = page.getByRole('heading', { name: '早上好，准备好开启新的一天了吗？' })
  try {
    await expect(heading).toBeVisible()
  } catch (error) {
    const diagnostics = await page.evaluate(async () => ({
      controller: Boolean(navigator.serviceWorker.controller),
      cacheEntries: await Promise.all((await caches.keys()).map(async key => ({ key, urls: (await (await caches.open(key)).keys()).map(request => new URL(request.url).pathname) }))),
      scripts: Array.from(document.scripts, script => script.src),
      appText: document.querySelector('#app')?.innerText,
      appMarkup: document.querySelector('#app')?.innerHTML.slice(0, 400),
    }))
    throw new Error(`Offline app shell did not render: ${JSON.stringify({ ...diagnostics, pageErrors })}; ${String(error)}`)
  }
  await expect(page.getByRole('button', { name: /企业$/ })).toBeVisible()
})

test('PWA keeps a complete hiring flow in one browser and isolates another browser', async ({ browser }) => {
  const a = await browser.newContext(), b = await browser.newContext()
  const pageA = await a.newPage(), pageB = await b.newPage()
  await pageA.goto('/')
  await expect(pageA.getByText('数据只保存在此浏览器')).toBeVisible()

  await pageA.getByRole('button', { name: '企业', exact: true }).click()
  await pageA.getByRole('button', { name: '新建企业' }).click()
  await pageA.getByLabel('企业名称').fill('本地验收企业')
  await pageA.getByRole('button', { name: '保存企业' }).click()
  await expect(pageA.getByText('本地验收企业', { exact: true })).toBeVisible()

  await pageA.getByRole('button', { name: '岗位', exact: true }).click()
  await pageA.getByRole('button', { name: '新建岗位' }).click()
  await openSelect(pageA, '所属企业')
  await pageA.getByText('本地验收企业', { exact: true }).last().click()
  await pageA.getByLabel('岗位名称').fill('浏览器本地工程师')
  await pageA.getByRole('button', { name: '保存岗位' }).click()
  await expect(pageA.locator('table').getByText('浏览器本地工程师')).toBeVisible()

  await pageA.getByRole('button', { name: '简历与材料', exact: true }).click()
  await pageA.getByRole('button', { name: '添加简历版本' }).click()
  await pageA.getByLabel('版本名称').fill('本地简历版本')
  await pageA.locator('input[type="file"][aria-label="简历附件"]').setInputFiles({ name: 'resume.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nlocal PWA acceptance') })
  await expect(pageA.getByText('附件已上传并绑定到版本')).toBeVisible()
  await pageA.getByRole('button', { name: '保存版本' }).click()
  await expect(pageA.getByText('本地简历版本')).toBeVisible()

  await pageA.getByRole('button', { name: '投递', exact: true }).click()
  await pageA.getByRole('button', { name: '新建投递' }).click()
  await openSelect(pageA, '岗位')
  await pageA.getByText(/本地验收企业 · 浏览器本地工程师/).click()
  await openSelect(pageA, '绑定简历版本')
  await pageA.getByText('本地简历版本', { exact: true }).last().click()
  await pageA.getByLabel('投递渠道').fill('官网')
  await pageA.getByRole('button', { name: '保存投递' }).click()
  await expect(pageA.locator('table').getByText('浏览器本地工程师')).toBeVisible()

  await pageA.locator('select').selectOption('面试中')
  await expect(pageA.locator('select')).toHaveValue('面试中')
  await pageA.getByRole('button', { name: '笔试与面试', exact: true }).click()
  await pageA.getByRole('button', { name: '面试', exact: true }).click()
  await pageA.getByRole('button', { name: '添加面试' }).click()
  await openSelect(pageA, '投递')
  await pageA.getByText(/本地验收企业 · 浏览器本地工程师/).last().click()
  const interviewDialog = pageA.getByRole('dialog', { name: '添加面试轮次' })
  await interviewDialog.getByLabel('轮次').fill('一面')
  const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000)
  await pageA.getByLabel('时间').fill(`${tomorrow.getFullYear()}-${String(tomorrow.getMonth()+1).padStart(2,'0')}-${String(tomorrow.getDate()).padStart(2,'0')}T10:00:00`)
  await interviewDialog.getByRole('button', { name: '保存面试' }).click()
  await expect(pageA.getByText('一面')).toBeVisible()

  await pageA.getByRole('button', { name: 'Offer', exact: true }).click()
  await pageA.getByRole('button', { name: '记录 Offer' }).click()
  await openSelect(pageA, '对应投递')
  await pageA.getByText(/本地验收企业 · 浏览器本地工程师/).last().click()
  await pageA.getByLabel('月薪').fill('20000')
  await pageA.getByRole('button', { name: '保存 Offer' }).click()
  await expect(pageA.locator('table').getByText('本地验收企业', { exact: true })).toBeVisible()
  await pageA.getByRole('button', { name: '数据分析', exact: true }).click()
  await expect(pageA.getByText('投递漏斗')).toBeVisible()

  await pageA.getByRole('button', { name: '日程', exact: true }).click()
  await pageA.getByRole('button', { name: '＋ 新建待办' }).click()
  await pageA.getByLabel('事项').fill('验证待办持久化')
  await pageA.getByRole('button', { name: '保存待办' }).click()
  await expect(pageA.getByText('验证待办持久化')).toBeVisible()
  await pageA.reload()
  await expect(pageA.getByText('已记录 1 条投递')).toBeVisible()
  await pageA.getByRole('button', { name: '企业', exact: true }).click()
  await expect(pageA.locator('table').getByText('本地验收企业', { exact: true })).toBeVisible()
  await pageA.getByRole('button', { name: '日程', exact: true }).click()
  await expect(pageA.getByText('验证待办持久化')).toBeVisible()

  await pageA.getByRole('button', { name: '设置', exact: true }).click()
  const downloadWait = pageA.waitForEvent('download')
  await pageA.getByRole('button', { name: '导出工作区备份' }).click()
  const download = await downloadWait
  const backupPath = await download.path()
  expect(backupPath).toBeTruthy()

  await pageB.goto('/')
  await pageB.getByRole('button', { name: '企业', exact: true }).click()
  await expect(pageB.getByText('尚无企业记录')).toBeVisible()
  await pageB.getByRole('button', { name: '设置', exact: true }).click()
  await pageB.locator('input[type=file]').last().setInputFiles(backupPath!)
  await expect(pageB.getByText(/已校验：/)).toBeVisible()
  pageB.once('dialog', dialog => dialog.accept())
  await pageB.getByRole('button', { name: '确认替换并恢复' }).click()
  await pageB.getByRole('button', { name: '企业', exact: true }).click()
  await expect(pageB.getByText('本地验收企业', { exact: true })).toBeVisible()
  await pageB.getByRole('button', { name: '岗位', exact: true }).click()
  await expect(pageB.getByText('浏览器本地工程师')).toBeVisible()
  await pageB.getByRole('button', { name: '简历与材料', exact: true }).click()
  await expect(pageB.getByText('本地简历版本')).toBeVisible()
  await pageB.getByRole('button', { name: '数据分析', exact: true }).click()
  await expect(pageB.getByText('投递漏斗')).toBeVisible()

  await pageB.getByRole('button', { name: '企业', exact: true }).click()
  pageB.once('dialog', dialog => dialog.accept())
  await pageB.getByRole('button', { name: '删除企业 本地验收企业' }).click()
  await expect(pageB.getByText('尚无企业记录')).toBeVisible()
  await pageB.getByRole('button', { name: '岗位', exact: true }).click()
  await expect(pageB.getByText('尚无岗位')).toBeVisible()
  await pageB.getByRole('button', { name: '投递', exact: true }).click()
  await expect(pageB.getByText('尚无投递记录')).toBeVisible()
  await pageB.getByRole('button', { name: '简历与材料', exact: true }).click()
  await expect(pageB.getByText('本地简历版本')).toBeVisible()
  await expect(pageB.getByRole('button', { name: '下载附件' })).toBeVisible()
  pageB.once('dialog', dialog => dialog.accept())
  await pageB.getByRole('button', { name: '删除简历附件' }).click()
  await expect(pageB.getByRole('button', { name: '下载附件' })).toHaveCount(0)
  pageB.once('dialog', dialog => dialog.accept())
  await pageB.getByRole('button', { name: '删除简历 本地简历版本' }).click()
  await expect(pageB.getByText('尚无简历版本')).toBeVisible()

  await a.close(); await b.close()
})

test('recruitment URL creates an editable manual draft but never auto-saves it', async ({ page }) => {
  await page.route('https://example.com/**', route => route.fulfill({ status: 200, contentType: 'text/html', body: '<title>Recruiting page</title>' }))
  await page.goto('/')
  await page.getByRole('button', { name: '企业', exact: true }).click()
  await page.getByRole('button', { name: '新建企业' }).click()
  await page.getByLabel('企业名称').fill('手工草稿验收')
  await page.getByRole('button', { name: '保存企业' }).click()
  await page.getByRole('button', { name: '招聘链接采集', exact: true }).click()
  await page.getByRole('textbox', { name: '招聘链接', exact: true }).fill('https://example.com/careers/role')
  await page.getByRole('button', { name: '打开链接并生成草稿' }).click()
  await expect(page.getByText(/纯浏览器 PWA 受招聘网站跨域限制/)).toBeVisible()
  await expect(page.getByLabel('职位描述（可编辑）')).toHaveValue(/请在新标签页打开招聘链接/)
  await page.getByRole('button', { name: '岗位', exact: true }).click()
  await expect(page.getByText('尚无岗位')).toBeVisible()
})

test('local document agent previews structured data and writes it only after confirmation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '资料 Agent', exact: true }).click()
  await page.locator('input[type=file]').setInputFiles({
    name: 'career-notes.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from('企业：Agent验收企业\n岗位：本地 Agent 验收工程师\n城市：苏州\n投递状态：已投递\n投递日期：2026-10-02\n投递渠道：官网\n下一步：准备项目经历介绍\n学校：测试大学\n专业：软件工程'),
  })
  await page.getByRole('button', { name: '读取并整理文档' }).click()
  await expect(page.getByRole('heading', { name: '确认导入内容' })).toBeVisible()
  await expect(page.getByText('企业 · 企业', { exact: true })).toBeVisible()
  await expect(page.getByText('岗位 · 岗位', { exact: true })).toBeVisible()
  await expect(page.getByText('投递进展 · 投递进展', { exact: true })).toBeVisible()

  const recordsBefore = await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open('hire-cockpit-local')
      request.onsuccess = () => resolve(request.result)
      request.onerror = () => reject(request.error)
    })
    const count = async (table: string) => new Promise<number>((resolve, reject) => {
      const request = db.transaction('records').objectStore('records').index('table').count(table)
      request.onsuccess = () => resolve(request.result)
      request.onerror = () => reject(request.error)
    })
    const result = { companies: await count('companies'), jobs: await count('jobs'), applications: await count('applications'), tasks: await count('tasks'), profiles: await count('profiles') }
    db.close()
    return result
  })
  expect(recordsBefore).toEqual({ companies: 0, jobs: 0, applications: 0, tasks: 0, profiles: 0 })

  await page.getByRole('button', { name: '确认并写入本机' }).click()
  await expect(page.getByText(/已确认并保存 5 项到本机工作区/)).toBeVisible()
  await page.getByRole('button', { name: '投递', exact: true }).click()
  await expect(page.getByText('本地 Agent 验收工程师')).toBeVisible()
  await page.getByRole('button', { name: '日程', exact: true }).click()
  await expect(page.getByText('准备项目经历介绍')).toBeVisible()
  await page.getByRole('button', { name: '个人资料', exact: true }).click()
  await expect(page.getByText('测试大学')).toBeVisible()
})

test('job match agent scores a pasted listing locally and requires confirmation before saving', async ({ page }) => {
  const externalRequests: string[] = []
  page.on('request', request => { if (!request.url().startsWith('http://127.0.0.1')) externalRequests.push(request.url()) })
  await page.goto('/')
  await page.getByRole('button', { name: '岗位匹配 Agent', exact: true }).click()
  await page.getByLabel('目标岗位方向（逗号或顿号分隔）').fill('后端研发')
  await page.getByLabel('目标城市').fill('杭州')
  await page.getByLabel('必须出现的条件').fill('Java')
  await page.getByLabel('加分关键词').fill('Spring')
  await page.getByLabel('排除关键词').fill('外包')
  await page.getByLabel('期望最低月薪（元，可留空）').fill('15000')
  await page.getByLabel('期望最高月薪（元，可留空）').fill('30000')
  await openSelect(page, '我的学历')
  await page.getByText('本科', { exact: true }).last().click()
  await page.getByRole('button', { name: '保存匹配偏好' }).click()
  await expect(page.getByText('求职偏好已保存到本机。')).toBeVisible()

  await page.getByPlaceholder(/公司：海风科技/).fill('公司：本地匹配验收企业\n职位：后端研发工程师\n城市：杭州\n薪资：18k-28k\n学历要求：本科\n技能要求：Java、Spring\n招聘链接：https://example.com/jobs/backend')
  await page.getByRole('button', { name: '本地解析并评估' }).click()
  await expect(page.getByText(/本地匹配：\d+ 分 · 优先查看/)).toBeVisible()
  await expect(page.getByText(/已找到必需条件：“Java”/)).toBeVisible()
  await expect(page.getByText(/薪资范围符合/)).toBeVisible()
  await expect(page.getByRole('button', { name: '确认并加入本机岗位库' })).toBeEnabled()
  const jobsBeforeConfirmation = await page.evaluate(async () => new Promise<number>((resolve, reject) => {
    const open = indexedDB.open('hire-cockpit-local')
    open.onsuccess = () => { const db = open.result, count = db.transaction('records').objectStore('records').index('table').count('jobs'); count.onsuccess = () => { db.close(); resolve(count.result) }; count.onerror = () => reject(count.error) }
    open.onerror = () => reject(open.error)
  }))
  expect(jobsBeforeConfirmation).toBe(0)

  await page.getByRole('button', { name: '确认并加入本机岗位库' }).click()
  await expect(page.getByText('已确认并加入本机岗位库。')).toBeVisible()
  await page.getByRole('button', { name: '岗位', exact: true }).click()
  await expect(page.getByText('后端研发工程师')).toBeVisible()
  expect(externalRequests).toEqual([])

  await page.getByRole('button', { name: '岗位匹配 Agent', exact: true }).click()
  await page.getByPlaceholder(/公司：海风科技/).fill('公司：被排除的验收企业\n职位：后端研发工程师\n城市：杭州\n薪资：18k-28k\n学历要求：本科\n技能要求：Java、Spring\n岗位描述：外包驻场')
  await page.getByRole('button', { name: '本地解析并评估' }).click()
  await expect(page.getByText(/本地匹配：\d+ 分 · 暂不匹配/)).toBeVisible()
  await expect(page.getByRole('button', { name: '确认并加入本机岗位库' })).toBeDisabled()
  await page.getByText('我已核对排除原因，仍要将此岗位保存为普通记录').click()
  await expect(page.getByRole('button', { name: '确认并加入本机岗位库' })).toBeEnabled()
})

test('local application workflow pauses, resumes, cancels, approves, records, and schedules with an audit trail', async ({ page }) => {
  page.on('dialog', dialog => { void dialog.accept() })
  const externalRequests: string[] = []
  page.on('request', request => { if (!request.url().startsWith('http://127.0.0.1')) externalRequests.push(request.url()) })
  await page.goto('/')
  await page.getByRole('button', { name: '企业', exact: true }).click()
  await page.getByRole('button', { name: '新建企业' }).click()
  await page.getByLabel('企业名称').fill('工作流验收企业')
  await page.getByRole('button', { name: '保存企业' }).click()
  await page.getByRole('button', { name: '岗位', exact: true }).click()
  await page.getByRole('button', { name: '新建岗位' }).click()
  await openSelect(page, '所属企业')
  await page.getByText('工作流验收企业', { exact: true }).last().click()
  await page.getByLabel('岗位名称').fill('工作流验收后端工程师')
  await page.getByRole('button', { name: '保存岗位' }).click()

  await page.getByRole('button', { name: '投递工作流', exact: true }).click()
  await page.getByRole('button', { name: '配置模板' }).click()
  await page.getByLabel('默认跟进间隔（天）').fill('2')
  await page.getByRole('button', { name: '保存模板' }).click()
  await page.locator('.workflow-start .el-select').click()
  await page.getByText(/工作流验收企业 · 工作流验收后端工程师/).last().click()
  await page.getByRole('button', { name: '启动本地投递流程' }).click()
  await expect(page.getByText('岗位匹配：0 分 · 需要核对')).toBeVisible()
  await page.getByRole('button', { name: '暂停' }).click()
  const workflowStatus = () => page.evaluate(async () => new Promise<string>((resolve, reject) => {
    const open = indexedDB.open('hire-cockpit-local')
    open.onsuccess = () => { const db = open.result, request = db.transaction('records').objectStore('records').index('table').getAll('workflowRuns'); request.onsuccess = () => { const rows = request.result.map((row: any) => row.value); db.close(); resolve(rows[0]?.status || 'missing') }; request.onerror = () => reject(request.error) }
    open.onerror = () => reject(open.error)
  }))
  await expect.poll(workflowStatus).toBe('paused')
  await expect(page.locator('.workflow-run-card').first().locator('.workflow-run-heading .el-tag')).toHaveText('已暂停')
  await page.getByRole('button', { name: '恢复' }).click()
  await expect.poll(workflowStatus).toBe('running')
  await page.getByRole('button', { name: '撤销工作流' }).click()
  await expect(page.locator('.workflow-run-card').first().locator('.workflow-run-heading .el-tag')).toHaveText('已撤销')
  await page.locator('.workflow-history summary').first().click()
  await expect(page.getByText('撤销工作流', { exact: true })).toBeVisible()

  await page.locator('.workflow-start .el-select').click()
  await page.getByText(/工作流验收企业 · 工作流验收后端工程师/).last().click()
  await page.getByRole('button', { name: '启动本地投递流程' }).click()
  const run = page.locator('.workflow-run-card').first()
  await expect(run.locator('.workflow-action > b')).toHaveText('准备申请材料')
  await run.locator('textarea').fill('已为岗位调整项目排序并核对教育经历')
  await run.getByRole('button', { name: '完成材料准备' }).click()
  await run.getByRole('button', { name: '批准进入人工投递阶段' }).click()
  await run.getByPlaceholder('实际投递渠道：招聘官网、BOSS直聘、内推等').fill('企业招聘官网')
  await run.getByRole('button', { name: '确认已人工提交并登记投递' }).click()
  await expect(run.getByText('安排跟进')).toBeVisible()
  await run.getByRole('button', { name: '创建跟进待办并完成流程' }).click()
  await expect(run.locator('.workflow-run-heading .el-tag')).toHaveText('已完成')
  await run.locator('.workflow-history summary').click()
  await expect(run.getByText(/创建跟进待办/)).toBeVisible()
  expect(externalRequests).toEqual([])

  await page.reload()
  await page.getByRole('button', { name: '投递工作流', exact: true }).click()
  await expect(page.locator('.workflow-run-card').first().locator('.workflow-run-heading .el-tag')).toHaveText('已完成')
  await page.getByRole('button', { name: '投递', exact: true }).click()
  await expect(page.getByText('工作流验收后端工程师')).toBeVisible()
  await page.getByRole('button', { name: '日程', exact: true }).click()
  await expect(page.getByText(/跟进 工作流验收企业 · 工作流验收后端工程师 投递/).first()).toBeVisible()
})
