import { test, expect } from '@playwright/test'

test('independent browser workspaces cannot read or mutate each other', async ({ browser }) => {
  const a = await browser.newContext(), b = await browser.newContext()
  const pageA = await a.newPage(), pageB = await b.newPage()
  await pageA.goto('/'); await expect(pageA.getByText('仅此浏览器可继续使用')).toBeVisible()
  await pageA.getByRole('button', { name: '企业', exact: true }).click()
  await pageA.getByRole('button', { name: '新建企业' }).click()
  await pageA.getByLabel('企业名称').fill('隔离验收企业')
  await pageA.getByRole('button', { name: '保存企业' }).click()
  await expect(pageA.getByText('隔离验收企业')).toBeVisible()
  await pageA.getByRole('button', { name: '岗位', exact: true }).click()
  await pageA.getByRole('button', { name: '新建岗位' }).click()
  await pageA.getByLabel('所属企业').click(); await pageA.getByText('隔离验收企业', { exact: true }).last().click()
  await pageA.getByLabel('岗位名称').fill('全栈工程师')
  await pageA.getByRole('button', { name: '保存岗位' }).click()
  await expect(pageA.getByText('全栈工程师')).toBeVisible()
  await pageA.getByRole('button', { name: '简历与材料', exact: true }).click()
  await pageA.getByRole('button', { name: '添加简历版本' }).click()
  await pageA.getByLabel('版本名称').fill('后端研发校招版')
  await pageA.getByRole('button', { name: '保存版本' }).click()
  await expect(pageA.getByText('后端研发校招版')).toBeVisible()
  await pageA.getByRole('button', { name: '投递', exact: true }).click()
  await pageA.getByRole('button', { name: '新建投递' }).click()
  await pageA.getByLabel('岗位').click(); await pageA.getByText(/隔离验收企业 · 全栈工程师/).click()
  await pageA.getByLabel('绑定简历版本').click(); await pageA.getByText('后端研发校招版', { exact: true }).last().click()
  await pageA.getByRole('button', { name: '保存投递' }).click()
  await expect(pageA.getByText('全栈工程师')).toBeVisible()
  await pageA.locator('select').selectOption('面试中')
  await expect(pageA.locator('select')).toHaveValue('面试中')
  const owned = await pageA.evaluate(async () => ({
    apps: await (await fetch('/api/v1/applications')).json(),
    companies: await (await fetch('/api/v1/companies')).json()
  }))
  expect(owned.apps).toHaveLength(1)
  await pageA.reload()
  await expect(pageA.getByText('仅此浏览器可继续使用')).toBeVisible()
  await pageA.getByRole('button', { name: '企业', exact: true }).click()
  await expect(pageA.getByText('隔离验收企业')).toBeVisible()

  await pageB.goto('/'); await expect(pageB.getByText('仅此浏览器可继续使用')).toBeVisible()
  await pageB.getByRole('button', { name: '企业', exact: true }).click()
  await expect(pageB.getByText('尚无企业记录')).toBeVisible()
  const crossWorkspace = await pageB.evaluate(async ({ companyId, applicationId }) => {
    const headers = { 'Content-Type': 'application/json', 'X-CSRF-Token': decodeURIComponent(document.cookie.split('; ').find(c => c.startsWith('hc_csrf='))!.slice(8)) }
    const companyPost = await fetch('/api/v1/jobs', { method: 'POST', headers, body: JSON.stringify({ companyId, title: '越权岗位' }) })
    const applicationGet = await fetch(`/api/v1/applications/${applicationId}/history`)
    const applicationMutation = await fetch(`/api/v1/applications/${applicationId}/status`, { method: 'PUT', headers, body: JSON.stringify({ status: '已拿 Offer', stage: 'OFFER' }) })
    return { companyPost: companyPost.status, applicationGet: applicationGet.status, applicationMutation: applicationMutation.status }
  }, { companyId: owned.companies[0].id, applicationId: owned.apps[0].id })
  expect(crossWorkspace.companyPost).toBe(404)
  expect(crossWorkspace.applicationGet).toBe(404)
  expect(crossWorkspace.applicationMutation).toBe(404)
  await a.close(); await b.close()
})
